### ISSUE TITLE
VO injects uberon axiom causing incoherency

### ISSUE THREAD

**Issue by cmungall** [vaccineontology/VO#1]
VO says anatomical entity (uberon) subClassOf material entity (bfo)

![image](https://user-images.githubusercontent.com/50745/60535880-ef594a80-9cb9-11e9-97ed-72a9e8f4fc75.png)

this is false and causes incoherency when VO is combined with the real uberon

can you fix this, and also provide a base module that others can use in their imports?

**Comment by zhengj2007** [comment]
Fixed
