### ISSUE TITLE
new term request

### ISSUE THREAD

**Issue by rvita** [vaccineontology/VO#13]
I'd like to request this new vaccine term:
Ad35.CS.01   malaria vaccine
see details in attached template.
[VO_requests12_2020.xlsx](https://github.com/vaccineontology/VO/files/5676209/VO_requests12_2020.xlsx)
Thanks,
Randi

**Comment by yongqunh** [comment]
The term 'Ad35.CS.01 malaria vaccine' is assigned  the VO ID: VO_0004993
http://purl.obolibrary.org/obo/VO_0004993
The updated VO has been submitted, and should be shown up in Ontobee within one day or two.
