### ISSUE TITLE
VAC: 1V270

### ISSUE THREAD

**Issue by yongqunh** [vaccineontology/VO#22]
Request to add a new vaccine adjuvant as seen in VAC: 
https://vac.niaid.nih.gov/view?id=6

PubMed references:
https://pubmed.ncbi.nlm.nih.gov/28724768/
https://pubmed.ncbi.nlm.nih.gov/25568203/

**Comment by yongqunh** [comment]
A new VO ID added: 
http://purl.obolibrary.org/obo/VO_0005270 

Definition: 
IV270 is a low–molecular weight TLR7 agonist conjugated to a phospholipid and is a highly potent and stable immune activator

**Comment by amoghmadireddi** [comment]
Chemical Nature: Small molecule
Receptor: TLR7
Mechanism of Action: Activation of innate immune pathways
Immune profile induced: Th1-biased
Other Features/Characteristics: (1) Induces mucosal immunity, (2) Induces CD8 T cells, (3) Induces epitope spreading, (4) Provides innate protection, (5) Promotes antibody affinity maturation, (6) Promotes antibody epitope spreading By routes: intramuscular and intranasal.
Point of Contact: Dennis Carson, UCSD
