### ISSUE TITLE
VAC: Adjuplex+GLA

### ISSUE THREAD

**Issue by amoghmadireddi** [vaccineontology/VO#26]
Request to add a new vaccine adjuvant as seen in VAC:
[https://vac.niaid.nih.gov/view?id=15](https://vac.niaid.nih.gov/view?id=15)

Pubmed References:
[https://www.ncbi.nlm.nih.gov/pubmed/?term=32984856](https://www.ncbi.nlm.nih.gov/pubmed/?term=32984856)
[https://www.ncbi.nlm.nih.gov/pubmed/?term=33767689](https://www.ncbi.nlm.nih.gov/pubmed/?term=33767689)
[https://www.ncbi.nlm.nih.gov/pubmed/?term=33444400](https://www.ncbi.nlm.nih.gov/pubmed/?term=33444400)

**Comment by amoghmadireddi** [comment]
Chemical Nature: (1) Synthetic derivative of natural compound, (2) Emulsion, (3) Combination adjuvant, (4) Other
Receptor: TLR4
Mechanism of Action: Adjuplex enhances cross presentation to CD8 T cells and GLA stimulates TLR4 signaling
Immune profile induced: Mixed Th1/Th17
Other Features/Characteristics: None
Point of Contact: Marulasiddappa Suresh, UW Madison

**Comment by yongqunh** [comment]
VO ID assigned: http://purl.obolibrary.org/obo/VO_0005302
