### ISSUE TITLE
VAC: Alhydroxiquim-II

### ISSUE THREAD

**Issue by amoghmadireddi** [vaccineontology/VO#27]
Request to add a new vaccine adjuvant as seen in VAC:
[https://vac.niaid.nih.gov/view?id=12](https://vac.niaid.nih.gov/view?id=12)

Pubmed References:
[https://www.ncbi.nlm.nih.gov/pubmed/?term=33521604](https://www.ncbi.nlm.nih.gov/pubmed/?term=33521604)
[https://www.ncbi.nlm.nih.gov/pubmed/?term=33654090](https://www.ncbi.nlm.nih.gov/pubmed/?term=33654090)

**Comment by amoghmadireddi** [comment]
Chemical Nature: Small molecule
Receptor: (1) TLR7, (2) TLR8
Mechanism of Action: TLR7/8 dual agonist - lymph node delivery
Immune profile induced: Th1-biased
Other Features/Characteristics: Promotes antibody affinity maturation
Point of Contact: Sunil David, Virovax

**Comment by yongqunh** [comment]
VO ID assigned: http://purl.obolibrary.org/obo/VO_0005301
