### ISSUE TITLE
Cancer DNA Vaccine pSURV encoding Survivin

### ISSUE THREAD

**Issue by ISeleznev822** [vaccineontology/VO#318]
Vaccine name: Cancer DNA Vaccine pSURV encoding Survivin
Vaccine type: DNA vaccine
Cancer type: n/a
Host species: Human, mouse tested
Vaccine status: Research
Description: n/a
Immunization route: Intradermal injection (i.d.)
PubMed: 19526360
PubMed link: https://pubmed.ncbi.nlm.nih.gov/19526360/
Gene/protein:  Survivin (NCBI: 2315863)
VIOLIN link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=1053&keywords=

**Comment by yongqunh** [comment]
Gene information:
Survivin
http://www.violinet.org/vaxgen/gene_detail.php?c_gene_id=719
