### ISSUE TITLE
VAC: CaPNP (CaPtivant)(TM)

### ISSUE THREAD

**Issue by amoghmadireddi** [vaccineontology/VO#34]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=11

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=31591662
https://www.ncbi.nlm.nih.gov/pubmed/?term=28933657
https://www.ncbi.nlm.nih.gov/pubmed/?term=28716554
https://www.ncbi.nlm.nih.gov/pubmed/?term=11063495
https://www.ncbi.nlm.nih.gov/pubmed/?term=12204953

**Comment by amoghmadireddi** [comment]
Chemical Nature: Synthetic derivative of natural compound
Receptor: Unknown
Mechanism of Action: (1) Antigen carrier, (2) Innate immune enhancer/activator
Immune profile induced: Mixed Th1/Th2
Other Features/Characteristics: (1) Induces mucosal immunity, (2) Induces CD8 T cells, (3) Provides innate protection, (4) Other, (5) Promotes antibody affinity maturation, (6) High stability. By routes: IM, IN, IP, IN, ID, IVag. Specify: Safe for systemic or mucosal administration
Point of Contact: Tulin Morcol, Captivate Pharma

**Comment by yongqunh** [comment]
VO ID assigned: http://purl.obolibrary.org/obo/VO_0005295
