### ISSUE TITLE
VAC: DDO (Defective viral genome-Derived Oligonucleotide)

### ISSUE THREAD

**Issue by amoghmadireddi** [vaccineontology/VO#35]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=30

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=24099876
https://www.ncbi.nlm.nih.gov/pubmed/?term=29861183

**Comment by amoghmadireddi** [comment]
Chemical Nature: (1) Synthetic derivative of natural compound, (2) Nucleic acid
Receptor: TLR3
Mechanism of Action: TLR3, possibly RIG-I - agonist
Immune profile induced: Th1-biased
Other Features/Characteristics: (1) Induces mucosal immunity, (2) Induces CD8 T cells, (3) Provides innate protection. By routes: SQ, IM.
Point of Contact: Carolina Lopez, University of Washington at St Louis

**Comment by yongqunh** [comment]
VO ID assigned: http://purl.obolibrary.org/obo/VO_0005294
