### ISSUE TITLE
VAC: Em

### ISSUE THREAD

**Issue by amoghmadireddi** [vaccineontology/VO#36]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=18

Pubmed References:
None

**Comment by amoghmadireddi** [comment]
Chemical Nature: Emulsion
Receptor: Unknown
Mechanism of Action: Squalene emulsion possibly triggering inflammasome or through extracellular ATP
Immune profile induced: None
Other Features/Characteristics: None
Point of Contact: Darrick Carter, PAI Life Sciences

**Comment by yongqunh** [comment]
VO ID assigned: http://purl.obolibrary.org/obo/VO_0005293
