### ISSUE TITLE
PRotein Ontology class identifiers labeled with PRO instead PR

### ISSUE THREAD

**Issue by callahantiff** [vaccineontology/VO#4]
I noticed that there are 2 ontology classes (listed below) that include `PRO` instead of `PR` in the identifier.
- protein - [PRO:000000001](http://purl.obolibrary.org/obo/PRO_000000001)  
- superoxide dismutase [Cu-Zn] - [PRO:000015399](http://purl.obolibrary.org/obo/PRO_000015399)  

I'm curious why you chose to use `PRO` instead of using `PR` which would be consistent with the way these classes are defined in the PRotein Ontology?

**Comment by yongqunh** [comment]
PRO was old annotation style. We should use PR instead. Thanks for pointing this out.

**Comment by zhengj2007** [comment]
Fixed.
