### ISSUE TITLE
Telomerase Peptide Vaccine GV1001

### ISSUE THREAD

**Issue by virginiayyhe** [vaccineontology/VO#416]
Vaccine name: Telomerase Peptide Vaccine GV1001
Vaccine Type: Other
Cancer type: various
Host Species : Human clinical trial, mouse tested
Status: Clinical trial
Description: A synthetic peptide vaccine, containing 16 amino acid residues (611-626) of the human telomerase reverse transcriptase catalytic subunit (hTERT), with potential antineoplastic activity. Telomerase, a reverse transcriptase normally repressed in healthy cells, is overexpressed in most cancer cells and plays a key role in cellular proliferation. Vaccination with the telomerase peptide GV1001 may activate the immune system to mount a cytotoxic T-lymphocyte (CTL) response against telomerase-expressing cells.
Immunization Route: n/a
PubMed: 27941629
PumMed Link: https://pubmed.ncbi.nlm.nih.gov/27941629/
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5101&keywords=Telomerase%20Peptide%20Vaccine%20GV1001

**Comment by yongqunh** [comment]
http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5101
