### ISSUE TITLE
VAC: Mannadjuvant

### ISSUE THREAD

**Issue by amoghmadireddi** [vaccineontology/VO#43]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=14

Pubmed References:
None

**Comment by amoghmadireddi** [comment]
Chemical Nature: (1) Natural compound, (2) Carbohydrate, (3) Combination adjuvant
Receptor: CLR (Dectin, Mincle) and NAIP
Mechanism of Action: Activation of Dectin-2-expressing innate immune cells; dual targeting of injection site and draining lymph node.
Immune profile induced: Mixed Th1/Th2
Other Features/Characteristics: Promotes antibody epitope spreading
Point of Contact: Ivan Zanoni, Boston Children's Hospital

**Comment by yongqunh** [comment]
VO ID assigned: http://purl.obolibrary.org/obo/VO_0005286
