### ISSUE TITLE
VAC: Advax

### ISSUE THREAD

**Issue by wolfgang-leitner** [vaccineontology/VO#443]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=37

Pubmed References:Chemical Nature: Carbohydrate
Mechanism of Action: Complement, Dendritic cells (unknown receptor), Other, Unknown
Immune profile induced: mixed Th1/Th2
By routes: IM, IN, IP, SQ, inhalation, 
Point of Contact: Nikolai Petrovsky, Vaxine
https://www.ncbi.nlm.nih.gov/pubmed/?term=31009889
https://www.ncbi.nlm.nih.gov/pubmed/?term=25520500
https://www.ncbi.nlm.nih.gov/pubmed/?term=28758637
https://www.ncbi.nlm.nih.gov/pubmed/?term=23864620
https://www.ncbi.nlm.nih.gov/pubmed/?term=24342245
https://www.ncbi.nlm.nih.gov/pubmed/?term=23306367
https://www.ncbi.nlm.nih.gov/pubmed/?term=21147758
https://www.ncbi.nlm.nih.gov/pubmed/?term=15479440
https://www.ncbi.nlm.nih.gov/pubmed/?term=26031451
https://www.ncbi.nlm.nih.gov/pubmed/?term=25659269
https://www.ncbi.nlm.nih.gov/pubmed/?term=33883559
https://www.ncbi.nlm.nih.gov/pubmed/?term=30312742
https://www.ncbi.nlm.nih.gov/pubmed/?term=21736913
https://www.ncbi.nlm.nih.gov/pubmed/?term=30218687
https://www.ncbi.nlm.nih.gov/pubmed/?term=25459531
https://www.ncbi.nlm.nih.gov/pubmed/?term=24958701
https://www.ncbi.nlm.nih.gov/pubmed/?term=25516480
https://www.ncbi.nlm.nih.gov/pubmed/?term=20130134
https://www.ncbi.nlm.nih.gov/pubmed/?term=23388724
https://www.ncbi.nlm.nih.gov/pubmed/?term=21169215
https://www.ncbi.nlm.nih.gov/pubmed/?term=30832356
https://www.ncbi.nlm.nih.gov/pubmed/?term=30322015
https://www.ncbi.nlm.nih.gov/pubmed/?term=28602608
https://www.ncbi.nlm.nih.gov/pubmed/?term=28676380
https://www.ncbi.nlm.nih.gov/pubmed/?term=33542494
https://www.ncbi.nlm.nih.gov/pubmed/?term=26232344
https://www.ncbi.nlm.nih.gov/pubmed/?term=22728225
https://www.ncbi.nlm.nih.gov/pubmed/?term=22728225
https://www.ncbi.nlm.nih.gov/pubmed/?term=25267153
https://www.ncbi.nlm.nih.gov/pubmed/?term=31300280
https://www.ncbi.nlm.nih.gov/pubmed/?term=28301280
https://www.ncbi.nlm.nih.gov/pubmed/?term=22717330
https://www.ncbi.nlm.nih.gov/pubmed/?term=26177480
https://www.ncbi.nlm.nih.gov/pubmed/?term=10000000
https://www.ncbi.nlm.nih.gov/pubmed/?term=27342914
https://www.ncbi.nlm.nih.gov/pubmed/?term=12

Clinical Trials:
https://clinicaltrials.gov/ct2/show/NCT01951677
https://clinicaltrials.gov/ct2/show/
https://clinicaltrials.gov/ct2/show/
https://clinicaltrials.gov/ct2/show/
https://clinicaltrials.gov/ct2/show/
https://clinicaltrials.gov/ct2/show/
https://clinicaltrials.gov/ct2/show/
https://clinicaltrials.gov/ct2/show/
https://clinicaltrials.gov/ct2/show/NCT01677676
https://clinicaltrials.gov/ct2/show/NCT01701752

**Comment by yongqunh** [comment]
A VO ID has been assigned to this vaccine before:
http://purl.obolibrary.org/obo/VO_0005207
New information has been added based on the provided VAC record.
