### ISSUE TITLE
VAC: dmLT

### ISSUE THREAD

**Issue by wolfgang-leitner** [vaccineontology/VO#444]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=13

Pubmed References:Chemical Nature: protein
Mechanism of Action: CGM1 ganglioside, cAMP, inflammasome
Immune profile induced: mixed Th1/Th17
Other Features/Characteristics: Induces mucosal immunity (IM, ID, SQ, SL, oral, , transcutaneous), Induces epitope spreading, Promotes antibody affinity maturation, Effective in newborns, promotes antibody epitope spreading
By routes: IM, ID, SL, oral, SQ, IN, IP, intragastric, transcutaneous, transdermal, buccal, intrarectal
Point of Contact: Elizabeth Norton, Tulane University

https://www.ncbi.nlm.nih.gov/pubmed/?term=21288994
https://www.ncbi.nlm.nih.gov/pubmed/?term=6803349
https://www.ncbi.nlm.nih.gov/pubmed/?term=26540197
https://www.ncbi.nlm.nih.gov/pubmed/?term=4927082
https://www.ncbi.nlm.nih.gov/pubmed/?term=26305793
https://www.ncbi.nlm.nih.gov/pubmed/?term=25111827
https://www.ncbi.nlm.nih.gov/pubmed/?term=24453241
https://www.ncbi.nlm.nih.gov/pubmed/?term=22202122
https://www.ncbi.nlm.nih.gov/pubmed/?term=25803825
https://www.ncbi.nlm.nih.gov/pubmed/?term=23541621
https://www.ncbi.nlm.nih.gov/pubmed/?term=26018536
https://www.ncbi.nlm.nih.gov/pubmed/?term=5461379
https://www.ncbi.nlm.nih.gov/pubmed/?term=3578125
https://www.ncbi.nlm.nih.gov/pubmed/?term=5216441
https://www.ncbi.nlm.nih.gov/pubmed/?term=19897067
https://www.ncbi.nlm.nih.gov/pubmed/?term=25944298
https://www.ncbi.nlm.nih.gov/pubmed/?term=6424635
https://www.ncbi.nlm.nih.gov/pubmed/?term=3916310
https://www.ncbi.nlm.nih.gov/pubmed/?term=4826740
https://www.ncbi.nlm.nih.gov/pubmed/?term=2884428
https://www.ncbi.nlm.nih.gov/pubmed/?term=30778066
https://www.ncbi.nlm.nih.gov/pubmed/?term=4893257
https://www.ncbi.nlm.nih.gov/pubmed/?term=28063704
https://www.ncbi.nlm.nih.gov/pubmed/?term=4375349
https://www.ncbi.nlm.nih.gov/pubmed/?term=28792004
https://www.ncbi.nlm.nih.gov/pubmed/?term=25765967
https://www.ncbi.nlm.nih.gov/pubmed/?term=25483682
https://www.ncbi.nlm.nih.gov/pubmed/?term=30638799
https://www.ncbi.nlm.nih.gov/pubmed/?term=21326197
https://www.ncbi.nlm.nih.gov/pubmed/?term=31757774
https://www.ncbi.nlm.nih.gov/pubmed/?term=31427449
https://www.ncbi.nlm.nih.gov/pubmed/?term=6957164
https://www.ncbi.nlm.nih.gov/pubmed/?term=33465933
https://www.ncbi.nlm.nih.gov/pubmed/?term=33465933
https://www.ncbi.nlm.nih.gov/pubmed/?term=33465933
https://www.ncbi.nlm.nih.gov/pubmed/?term=31641151
https://www.ncbi.nlm.nih.gov/pubmed/?term=27133878
https://www.ncbi.nlm.nih.gov/pubmed/?term=27676456
https://www.ncbi.nlm.nih.gov/pubmed/?term=27226279
https://www.ncbi.nlm.nih.gov/pubmed/?term=22406456
https://www.ncbi.nlm.nih.gov/pubmed/?term=30787109
https://www.ncbi.nlm.nih.gov/pubmed/?term=24403527
https://www.ncbi.nlm.nih.gov/pubmed/?term=24403527
https://www.ncbi.nlm.nih.gov/pubmed/?term=30563789
https://www.ncbi.nlm.nih.gov/pubmed/?term=31757774
https://www.ncbi.nlm.nih.gov/pubmed/?term=30473185
https://www.ncbi.nlm.nih.gov/pubmed/?term=30248001
https://www.ncbi.nlm.nih.gov/pubmed/?term=24049109
https://www.ncbi.nlm.nih.gov/pubmed/?term=30797634
https://www.ncbi.nlm.nih.gov/pubmed/?term=31482013
https://www.ncbi.nlm.nih.gov/pubmed/?term=29771685
https://www.ncbi.nlm.nih.gov/pubmed/?term=31757774
https://www.ncbi.nlm.nih.gov/pubmed/?term=25444830

Clinical trials:
https://clinicaltrials.gov/ct2/show/NCT03922061
https://clinicaltrials.gov/ct2/show/NCT04232943
https://clinicaltrials.gov/ct2/show/NCT02531685
https://clinicaltrials.gov/ct2/show/NCT02052934
https://clinicaltrials.gov/ct2/show/NCT02531802
https://clinicaltrials.gov/ct2/show/NCT01147445
https://clinicaltrials.gov/ct2/show/NCT03548064
https://clinicaltrials.gov/ct2/show/ NCT01739231
https://clinicaltrials.gov/ct2/show/NCT03404674
https://clinicaltrials.gov/ct2/show/NCT03729219
https://clinicaltrials.gov/ct2/show/NCT04826094

**Comment by yongqunh** [comment]
Assigned new VO ID:
http://purl.obolibrary.org/obo/VO_0005329
