### ISSUE TITLE
Missing Vaccine Role

### ISSUE THREAD

**Issue by Huffmaar** [vaccineontology/VO#5]
There is currently no 'Virus like particle vaccine' vaccine role within the VO.
Currently 'Energix B' (VO:0003266, VO:0003265, VO:0015020), each 'Virus like particle vaccine' does not have a role related to what type of vaccine it is.

**Comment by Huffmaar** [comment]
This would also likely require a new 'virus like particle vaccine' class to go along with the role.
This should probably amend 'Virus like particle vaccine role' as the vaccine role.

**Comment by Huffmaar** [comment]
I also found a new potential vaccine category: "T cell vaccine"or "T cell based vaccine". So far I have one new CoV vaccine that I plan on adding.

**Comment by yongqunh** [comment]
We added 'Virus-like particle vaccine' and 'Virus-like particle vaccine role' two terms today.
