### ISSUE TITLE
mRNA-Electroporated Dendritic Cells

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#543]
Vaccine name: mRNA-Electroporated Dendritic Cells
Vaccine Ontology ID: VO_0004614
Type: Dendritic cell
Status: Research
Host Species: Human
Description: NULL
Immunization Route: Intramuscular injection (i.m.)
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=4054&keywords=mRNA-Electroporated%20Dendritic%20Cells

**Comment by yongqunh** [comment]
This version is now added to VO:
http://purl.obolibrary.org/obo/VO_0004614 
It will be shown up after the latest VO is released.
Note: The vaccine name has been changed to:
mRNA-electroporated dendritic cells encoding gp100 and tyrosinase as melanoma vaccine

Penny and Oliver

**Comment by zhengj2007** [comment]
vaccine named as 'mRNA-electroporated dendritic cells encoding gp100 and tyrosinase as melanoma vaccine' in VIOLIN

Duplicated term was added in VO.
should merge VO_0007529 mRNA-Electroporated Dendritic Cells to VO_0004614 'mRNA-electroporated dendritic cells encoding gp100 and tyrosinase as melanoma vaccine'
and deprecate VO_0007529 mRNA-Electroporated Dendritic Cells
merge all annotations to VO_0004614
