### ISSUE TITLE
MUC-2-Globo H-KLH Conjugate Vaccine

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#546]
Vaccine name: MUC-2-Globo H-KLH Conjugate Vaccine
Type: Conjugate vaccine
Status: Clinical trial
Host Species: Human
Description: NULL
Immunization Route: n/a
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5126&keywords=MUC-2-Globo%20H-KLH%20Conjugate%20Vaccine

**Comment by yuanyp19** [comment]
Added to VO:http://purl.obolibrary.org/obo/VO_0005466
It will be shown in our next VO release.
