### ISSUE TITLE
MUC1 Antigen/SB AS-2

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#548]
Vaccine name: MUC1 Antigen/SB AS-2
Type: Other
Status: Clinical trial
Host Species: Human
Description: NULL
Immunization Route: n/a
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5123&keywords=MUC1%20Antigen/SB%20AS-2

**Comment by yuanyp19** [comment]
Added to VO:http://purl.obolibrary.org/obo/VO_0005464
It will be shown in our next VO release.
