### ISSUE TITLE
MUC1-KLH Conjugate Vaccine

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#549]
Vaccine name: MUC1-KLH Conjugate Vaccine
Type: Conjugate vaccine
Status: Clinical trial
Host Species: Human
Description: A peptide vaccine, containing human tumor-associated epithelial mucin (MUC1) conjugated with keyhole limpet hemocyanin (KLH), with potential antineoplastic activity. Vaccination with MUC1-KLH conjugate vaccine may stimulate humoral and cytotoxic T-lymphocyte (CTL) responses against tumor cells expressing the MUC1 antigen. In this vaccine, MUC1 antigen is conjugated with KLH, an immunostimulant and a hapten carrier, to enhance immune recognition. MUC1 antigen, a membrane-bound glycoprotein expressed by most glandular and ductal epithelial cells, is overexpressed in an aberrant or deglycosylated form in various cancers such as those of the breast, prostate, and ovary. (NCIT_C2232).
Immunization Route: n/a
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5251&keywords=MUC1-KLH%20Conjugate%20Vaccine

**Comment by yuanyp19** [comment]
Added to VO:http://purl.obolibrary.org/obo/VO_0005463
It will be shown in our next VO release.
