### ISSUE TITLE
MUC1-KLH Vaccine/QS21

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#550]
Vaccine name: MUC1-KLH Vaccine/QS21
Type: Other
Status: Clinical trial
Host Species: Human
Description: A peptide vaccine containing the human tumor-associated antigen epithelial mucin (MUC1 antigen) conjugated with keyhole limpet hemocyanin (KLH) and combined with the nonspecific immunoadjuvant QS21, with potential antineoplastic activity. MUC1 antigen is linked with KLH, an immunostimulant and a hapten carrier, in order to enhance immune recognition; the co-administration of saponin-derived QS21 potentially amplifies the total immune response to the MUC1 antigen. Administration of MUC1-KLH vaccine/QS21 may result in both the production of antitumor antibodies and the stimulation of a cytotoxic T-lymphocyte (CTL) response against tumor cells expressing the MUC1 antigen. MUC1 antigen, a membrane-bound glycoprotein expressed by most glandular and ductal epithelial cells, is overexpressed as an aberrant or deglycosylated form in various cancers such as breast, prostate and ovarian cancers. (NCIT_C11845).
Immunization Route: n/a
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5160&keywords=MUC1-KLH%20Vaccine/QS21

**Comment by yuanyp19** [comment]
Added to VO:http://purl.obolibrary.org/obo/VO_0005462
It will be shown in our next VO release.
