### ISSUE TITLE
MUC1-targeted Peptide GO-203-2C

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#551]
Vaccine name: MUC1-targeted Peptide GO-203-2C
Type: Other
Status: Clinical trial
Host Species: Human
Description: NULL
Immunization Route: n/a
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5068&keywords=MUC1-targeted%20Peptide%20GO-203-2C

**Comment by yuanyp19** [comment]
Added to VO:http://purl.obolibrary.org/obo/VO_0005461
It will be shown in our next VO release.
