### ISSUE TITLE
Multi-epitope Folate Receptor Alpha-loaded Dendritic Cell Vaccine

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#553]
Vaccine name: Multi-epitope Folate Receptor Alpha-loaded Dendritic Cell Vaccine
Type: Recombinant vector vaccine
Status: Clinical trial
Host Species: Human
Description: A cell-based vaccine composed of autologous-monocyte-derived dendritic cells (DCs) loaded with five immunogenic peptide epitopes, derived from the tumor-associated antigen human folate receptor alpha (FR alpha or FOLR1), including FR30, FR56, FR76, FR113, and FR238, with potential immunomodulatory and antineoplastic activity. Ex vivo treatment of the DCs with a p38 inhibitor decreases p38-mediated signaling and enhances ERK activation. This may allow, upon intradermal administration of the multi-epitope FR alpha-loaded DC vaccine into the patient, for decreased activation and expansion of CD4+ regulatory T-cells (Tregs), increased differentiation and expansion of interleukin-17 secreting T helper cells (Th17) and activation of CD8+ CTLs, which induces a strong anti-tumor T-cell immune response against FR alpha-overexpressing tumor cells. FR alpha is a high-affinity folate-binding protein and a member of the folate receptor family; this receptor is overexpressed in the majority of ovarian cancers and in about approximately 50% of breast cancers. (NCIT_C114990).
Immunization Route: n/a
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_comparison.php?displayOption=%2C&c_vaccine_id%5B%5D=5224&vaccine=ture&vaccine_c_proper_name=true&vaccine_c_brand_name=true&vaccine_c_manufacturer=true&vaccine_c_vo_id=true&vaccine_c_type=true&vaccine_c_status=true&vaccine_c_location_licensed=true&vaccine_c_host_species=true&vaccine_c_model_host=true&vaccine_c_antigen=true&vaccine_c_adjuvant=true&vaccine_c_vector=true&vaccine_c_preservative=true&vaccine_c_allergen=true&vaccine_c_preparation=true&vaccine_c_storage=true&vaccine_c_usage_age=true&vaccine_c_virulence=true&vaccine_c_contraindication=true&vaccine_c_description=true&gene_engineering=true&gene_engineering_c_type=true&gene_engineering_c_description=true&host_response=true&host_response_c_host_strain=checkbox&host_response_c_vaccination_protocol=checkbox&host_response_c_persistence=checkbox&host_response_c_immune_response_type=checkbox&host_response_c_immune_response_type2=checkbox&host_response_c_side_effects=checkbox&host_response_c_challenge_protocol=checkbox&host_response_c_protection_efficacy=checkbox&host_response_c_description=checkbox&vaccination_group=true&challenge=true&efficacy=true&host_gene_response=true&host_gene_response_c_description=true&Submit=Compare

**Comment by yuanyp19** [comment]
Added to VO:http://purl.obolibrary.org/obo/VO_0005459
It will be shown in our next VO release.
