### ISSUE TITLE
Multi-peptide CMV-Modified Vaccinia Ankara Vaccine

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#555]
Vaccine name: Multi-peptide CMV-Modified Vaccinia Ankara Vaccine
Type: Other
Status: Clinical trial
Host Species: Human
Description: NULL
Immunization Route: n/a
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5200&keywords=Multi-peptide%20CMV-Modified%20Vaccinia%20Ankara%20Vaccine

**Comment by yuanyp19** [comment]
Added to VO:http://purl.obolibrary.org/obo/VO_0005457
It will be shown in our next VO release.
