### ISSUE TITLE
Multipeptide Vaccine S-588210

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#556]
Vaccine name: Multipeptide Vaccine S-588210
Type: Other
Status: Clinical trial
Host Species: Human
Description: A cancer vaccine composed of a combination of the injectable formulations S-488210, which contains the three HLA-A*02:01-restricted peptides up-regulated lung cancer 10 (lymphocyte antigen 6K; LY6K; URLC10), cell division cycle-associated protein 1 (kinetochore protein Nuf2; NUF2; CDCA1) and insulin-like growth factor 2 mRNA-binding protein 3 (IGF2BP3; KOC1) and S-488211, which contains the two HLA-A*02:01-restricted peptides DEP domain-containing protein 1A (DEPDC1) and M-phase phosphoprotein 1 (kinesin-like protein KIF20B; MPHOSPH1), with potential immunostimulatory and antitumor activities. Upon administration, multipeptide vaccine S-588210 may stimulate a cytotoxic T-lymphocyte (CTL) response against tumor cells expressing KOC1, CDCA1, URLC10, DEPDC1 or MPHOSPH1 peptides, resulting in tumor cell lysis and decreased tumor growth. (NCIT_C125692).
Immunization Route: n/a
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5064&keywords=Multipeptide%20Vaccine%20S-588210

**Comment by yuanyp19** [comment]
Added to VO:http://purl.obolibrary.org/obo/VO_0005456
It will be shown in our next VO release.
