### ISSUE TITLE
Multivalent immunotherapeutic vaccine

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#557]
Vaccine name: Multivalent immunotherapeutic vaccine
Type: multivalent
Status: Research
Host Species: Human
Description: The approach focuses on the use of five primary patient derived melanoma cells (MEL-2, MEL-V, 3MM, KFM, and GLM-2). These cells display differential in vitro migratory and invasive properties as well as have the ability to form solid tumors when implanted into BALB/c nude mice. The retention of the innate phenotype of these primary patient derived cells together with the expression of a multitude repertoire of melanoma associated antigens offers a novel opportunity to target melanoma so as to avoid immune evasion (Suriano et al., 2013).
Immunization Route: Intramuscular injection (i.m.)
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=4064&keywords=Multivalent%20immunotherapeutic%20vaccine

**Comment by yuanyp19** [comment]
Added to VO:http://purl.obolibrary.org/obo/VO_0005455
It will be shown in our next VO release.
