### ISSUE TITLE
Mutant p53 Peptide Pulsed Dendritic Cell Vaccine

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#559]
Vaccine name: Mutant p53 Peptide Pulsed Dendritic Cell Vaccine
Type: Recombinant vector vaccine
Status: Clinical trial
Host Species: Human
Description: A cancer vaccine consisting of autologous dendritic cells which have been pulsed with a mutant p53 peptide. Vaccination with mutant p53 peptide pulsed dendritic cells may stimulate the host immune system to mount a cytotoxic T lymphocyte (CTL) response against tumor cells expressing mutant p53, resulting in tumor cell lysis. Many tumor cells overexpress mutant p53 proteins, resulting in the loss of apoptosis regulation and abnormal cell proliferation. (NCI04) (NCIT_C2540).
Immunization Route: n/a
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5364&keywords=Mutant%20p53%20Peptide%20Pulsed%20Dendritic%20Cell%20Vaccine

**Comment by yuanyp19** [comment]
Added to VO:http://purl.obolibrary.org/obo/VO_0005453
It will be shown in our next VO release.
