### ISSUE TITLE
VAC: Advax-CpG (Advax-2, Advax-SM)

### ISSUE THREAD

**Issue by wolfgang-leitner** [vaccineontology/VO#562]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=38

Pubmed References:Chemical Nature: (1) combination adjuvant
Mechanism of Action: (1) complement, (2) dendritic cells, (3) other/unknown, (4) TLR9
Immune profile induced: mixed Th1
Other Features/Characteristics: (1) induces CD8 T cells, (2) provides innate protection, (3) anti-inflammatory, (4) promotes antibody affinity maturation, (5) effective in newborns, (6) high stability
By routes: SQ, IM
Point of Contact: Nikolai Petrovsky, Vaxine LTD
https://www.ncbi.nlm.nih.gov/pubmed/?term=33301675
https://www.ncbi.nlm.nih.gov/pubmed/?term=33301675
https://www.ncbi.nlm.nih.gov/pubmed/?term=34069575
https://www.ncbi.nlm.nih.gov/pubmed/?term=32849580

**Comment by yongqunh** [comment]
Assigned VO ID:
http://purl.obolibrary.org/obo/VO_0005324

**Comment by wolfgang-leitner** [comment]
Please update name of this adjuvant to "Advax-CpG55.2".
PI has clarified that he is using the terms "Advax-2" and Advax-SM" for all combinations of Advax with a CpG ODN, not just CpG55.2.

**Comment by yongqunh** [comment]
I see. What about we keep the term Advax-CpG, and then add a new term "Advax-CpG55.2", which wil be a subclass term under Advax-CpG?

**Comment by wolfgang-leitner** [comment]
Hi Oliver, that’s a good idea! There will be additional Advax-CpG records coming in soon (all using the same Advax (ie, Inulin) but CpGs with different sequences).
Thanks!
Wolfgang

**Comment by yongqunh** [comment]
Hi Wolfgang,

That’s good. I will implement this idea then.

Thanks,
Oliver

**Comment by yongqunh** [comment]
In the current VO version, Advax-CpG55.2 has the VO ID: VO_0005324. 
http://purl.obolibrary.org/obo/VO_0005324
Advax-CpG, the higher "parent" level term, has the VO ID:  VO_0005357. 
http://purl.obolibrary.org/obo/VO_0005357

**Comment by yongqunh** [comment]
I checked Ontobee and found the VO vaccine adjuvant terms are loaded well. So I am going to close this issue.
