### ISSUE TITLE
MVF-HER-2(597-626)/MVF-HER-2 (266-296) Peptide Vaccine

### ISSUE THREAD

**Issue by Jusontin** [vaccineontology/VO#566]
Name: MVF-HER-2(597-626)/MVF-HER-2 (266-296) Peptide Vaccine
Type: Other
Status: Clinical trial
Host Species: Human
Description: A combination peptide vaccine of 2 chimeric peptides of the promiscuous T cell epitope derived from measles virus fusion protein (MVF; amino acid residues 288-302) co-synthesized with B-cell epitopes derived from the HER-2/neu a.a. 597-626 and HER-2/neu a.a. 266-296, with potential antineoplastic activity. Vaccination with MVF-HER-2(597-626)/MVF-HER-2(266-296) peptide vaccine may be capable of inducing an active specific immune response, mounting a cytotoxic T-lymphocyte (CTL) response and an antibody-dependent cell-mediated cytotoxicity (ADCC) against tumor cells that overexpress the HER-2 protein. The oncogenic protein HER-2, a member of the human epidermal growth factor receptor (EGFR) family of tyrosine kinases, is overexpressed in a variety of cancers and is correlated with increased tumor growth, progression and a poor prognosis. HER-2(597-626) corresponds to the binding site of trastuzumab on the extracellular domain IV of HER-2; HER-2 (266-296) corresponds to the binding site of pertuzumab on the dimerization loop of domain II of HER-2.
Immunization Route: n/a
PubMed: n/a
PumMed Link: n/a
Gene/protein: n/a
VIOLIN Link: http://www.violinet.org/canvaxkb/vaccine_comparison.php?displayOption=%2C&c_vaccine_id%5B%5D=5400&vaccine=ture&vaccine_c_proper_name=true&vaccine_c_brand_name=true&vaccine_c_manufacturer=true&vaccine_c_vo_id=true&vaccine_c_type=true&vaccine_c_status=true&vaccine_c_location_licensed=true&vaccine_c_host_species=true&vaccine_c_model_host=true&vaccine_c_antigen=true&vaccine_c_adjuvant=true&vaccine_c_vector=true&vaccine_c_preservative=true&vaccine_c_allergen=true&vaccine_c_preparation=true&vaccine_c_storage=true&vaccine_c_usage_age=true&vaccine_c_virulence=true&vaccine_c_contraindication=true&vaccine_c_description=true&gene_engineering=true&gene_engineering_c_type=true&gene_engineering_c_description=true&host_response=true&host_response_c_host_strain=checkbox&host_response_c_vaccination_protocol=checkbox&host_response_c_persistence=checkbox&host_response_c_immune_response_type=checkbox&host_response_c_immune_response_type2=checkbox&host_response_c_side_effects=checkbox&host_response_c_challenge_protocol=checkbox&host_response_c_protection_efficacy=checkbox&host_response_c_description=checkbox&vaccination_group=true&challenge=true&efficacy=true&host_gene_response=true&host_gene_response_c_description=true&Submit=Compare

**Comment by yuanyp19** [comment]
Added to VO:
http://purl.obolibrary.org/obo/VO_0005447
It will be shown in our next VO release.
