### ISSUE TITLE
VAC: LQ

### ISSUE THREAD

**Issue by wolfgang-leitner** [vaccineontology/VO#574]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=51

Chemical Nature: (1) other (liposome with Saponin)
Mechanism of Action: unknown
Immune profile induced: Th1-biased

Route of immunization: IM
Point of Contact: Patrice Dubois, Vaccine Formulation Institute

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=32156809
https://www.ncbi.nlm.nih.gov/pubmed/?term=33688647

**Comment by yongqunh** [comment]
VO ID generated: VO_0005390

http://purl.obolibrary.org/obo/VO_0005390
