### ISSUE TITLE
VAC: SQ

### ISSUE THREAD

**Issue by wolfgang-leitner** [vaccineontology/VO#575]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=52

Chemical Nature: (1) Emulsion (with Saponin)
Mechanism of Action: unknown
Immune profile induced: Th1-biased

Route of immunization: IM
Point of Contact: Patrice Dubois, Vaccine Formulation Institute

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=33688647

**Comment by yongqunh** [comment]
VO ID generated: VO_0005389

http://purl.obolibrary.org/obo/VO_0005389
