### ISSUE TITLE
VAC: SWE

### ISSUE THREAD

**Issue by wolfgang-leitner** [vaccineontology/VO#576]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=50

Chemical Nature: (1) emulsion
Mechanism of Action: unknown
Immune profile induced: Th1/Th17

Route of immunization: IM
Point of Contact: Patrice Dubois, Vaccine Formulation Institute

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=30849373
https://www.ncbi.nlm.nih.gov/pubmed/?term=32411401

Ongoing clinical trial:
https://clinicaltrials.gov/ct2/show/NCT04702178

**Comment by yongqunh** [comment]
VO ID generated: VO_0005388

http://purl.obolibrary.org/obo/VO_0005388
