### ISSUE TITLE
all COVID-19 vaccines are lack of the pathogen info

### ISSUE THREAD

**Issue by linikujp** [vaccineontology/VO#579]
All the COVID-19 vaccines are currently missing pathogen information
The 
owl:onProperty <http://purl.obolibrary.org/obo/VO_0003355>; owl:someValuesFrom SARS Cov-2 virus

immunizes against microbe VO_0003355

Where is the SARS Cov-2 Virus in the VO?

**Comment by Huffmaar** [comment]
There seems to be an issue that the proper NCBI taxonomy ID (according to ontobee) is present but without annotations. The most recent import file also did not have NCBItaxonomy ID, so it has been (re?)added. While it did not load, which suggest another error report, the annotations for SARS-CoV-2 were manually re-added in VO proper. It should be properly annotated now.
