### ISSUE TITLE
'Meruvax I' and 'Meruvax II' - both human vaccines?

### ISSUE THREAD

**Issue by linikujp** [vaccineontology/VO#580]
I believe that Meruvax I and Meruvax II are both human vaccines. Why only Meruvax II is annotated as human vaccine, but not Meruvax I?
Is it a bug to fix?

**Comment by Huffmaar** [comment]
Checking Meruvax I, it appears that both versions are human vaccines. Meruvax I appears to be an older version of Meruvax II. I have corrected that version in most recent update.

**Comment by linikujp** [comment]
Thank you, Anthony!

**Comment by yongqunh** [comment]
This issue appears fixed, so I am closing it.
