### ISSUE TITLE
VAC: Precision Vaccines Program (PVP)-037

### ISSUE THREAD

**Issue by AriJoffe** [vaccineontology/VO#586]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=56

Chemical Nature: small molecule
Mechanism of Action: Innate Immune Activation
Immune profile induced: Th1-biased

Route of immunization: IM 
Point of Contact: Ofer Levy, Precision Vaccines Program at Boston Children's Hospital

Pubmed References: n/a

Ongoing clinical trial: n/a

**Comment by yongqunh** [comment]
VO ID generated: VO_0005382

http://purl.obolibrary.org/obo/VO_0005382
