### ISSUE TITLE
VAC: Mast cell activator small molecules

### ISSUE THREAD

**Issue by AriJoffe** [vaccineontology/VO#587]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=54

Chemical Nature: small molecule
Mechanism of Action: mast cell activation
Immune profile induced: Th2-biased

Route of immunization: IN
Point of Contact: Herman Staats, Duke University

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=34566991

Ongoing clinical trial: n/a

**Comment by yongqunh** [comment]
VO ID generated: VO_0005381

http://purl.obolibrary.org/obo/VO_0005381
