### ISSUE TITLE
VAC: Mastoparan 7

### ISSUE THREAD

**Issue by AriJoffe** [vaccineontology/VO#588]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=53

Chemical Nature: peptide
Mechanism of Action: activation of mast cells, epithelial cells, macrophages and dendritic cells
Immune profile induced: Th2-biased

Route of immunization: IM and IN
Point of Contact: Herman Staats, Duke University

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=31068425
https://www.ncbi.nlm.nih.gov/pubmed/?term=34566991
https://www.ncbi.nlm.nih.gov/pubmed/?term=32047657

Ongoing clinical trial: n/a

**Comment by yongqunh** [comment]
VO term generated: VO_0005380

http://purl.obolibrary.org/obo/VO_0005380
