### ISSUE TITLE
VAC: PIKA

### ISSUE THREAD

**Issue by AriJoffe** [vaccineontology/VO#589]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=55

Chemical Nature: Nucleic Acid
Mechanism of Action: TLR/RLR-agonist
Immune profile induced: Th1/Th2

Route of immunization: IM and IN
Point of Contact: Xiaoliang Ren, Yisheng Bio

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=26765968
https://www.ncbi.nlm.nih.gov/pubmed/?term=20538850
https://www.ncbi.nlm.nih.gov/pubmed/?term=17484805
https://www.ncbi.nlm.nih.gov/pubmed/?term=34766005
https://www.ncbi.nlm.nih.gov/pubmed/?term=21468931
https://www.ncbi.nlm.nih.gov/pubmed/?term=28118938
https://www.ncbi.nlm.nih.gov/pubmed/?term=29174316

Ongoing clinical trial:
https://clinicaltrials.gov/ct2/show/NCT02657161
https://clinicaltrials.gov/ct2/show/NCT02956421

**Comment by yongqunh** [comment]
VO ID generated: VO_0005379 

http://purl.obolibrary.org/obo/VO_0005379
