### ISSUE TITLE
VAC: T-vant

### ISSUE THREAD

**Issue by AriJoffe** [vaccineontology/VO#590]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=58

Chemical Nature: other
Mechanism of Action: TLR4; inflammasome; DC activation
Immune profile induced: Th1/Th2/Th17

Route of immunization: IM and Oral
Point of Contact: Lisa Morici, Tulane University

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=34069796
https://www.ncbi.nlm.nih.gov/pubmed/?term=33498352

Ongoing clinical trial: n/a

**Comment by yongqunh** [comment]
The VO:T-vant term has been generated:
VO_0005375
http://purl.obolibrary.org/obo/VO_0005375 

Note: after double check, the VAC ID for this vaccine adjuvant should be 61 (not 58): 
https://vac.niaid.nih.gov/view?id=61
