### ISSUE TITLE
VAC: SLA-SE

### ISSUE THREAD

**Issue by AriJoffe** [vaccineontology/VO#593]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=65

Chemical Nature: other
Mechanism of Action: TLR4; Innate Immune Activation
Immune profile induced: n/a

Route of immunization: IM
Point of Contact: Christopher Fox, AAHI

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=32540272
https://www.ncbi.nlm.nih.gov/pubmed/?term=35459225
https://www.ncbi.nlm.nih.gov/pubmed/?term=31149350
https://www.ncbi.nlm.nih.gov/pubmed/?term=30386348
https://www.ncbi.nlm.nih.gov/pubmed/?term=31891152

Ongoing clinical trial:
https://clinicaltrials.gov/ct2/show/NCT03820414
https://clinicaltrials.gov/ct2/show/NCT02071758

**Comment by yongqunh** [comment]
Added to VO:
http://purl.obolibrary.org/obo/VO_0005423
