### ISSUE TITLE
VAC: SLA-LSQ

### ISSUE THREAD

**Issue by AriJoffe** [vaccineontology/VO#594]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=64

Chemical Nature: other
Mechanism of Action: TLR4; Innate Immune Activation
Immune profile induced: Th1-biased

Route of immunization: IM
Point of Contact: Christopher Fox, AAHI

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=30302281

Ongoing clinical trial: n/a

**Comment by yongqunh** [comment]
Added to VO:
http://purl.obolibrary.org/obo/VO_0005422
