### ISSUE TITLE
VAC: GLA-SLQ

### ISSUE THREAD

**Issue by AriJoffe** [vaccineontology/VO#595]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=63

Chemical Nature: other
Mechanism of Action: TLR4; Innate Immune Activation
Immune profile induced: Mixed Th1/Th2

Route of immunization: IM
Point of Contact: Christopher Fox, AAHI

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=24551202
https://www.ncbi.nlm.nih.gov/pubmed/?term=24465426
https://www.ncbi.nlm.nih.gov/pubmed/?term=24551202
https://www.ncbi.nlm.nih.gov/pubmed/?term=31174937
https://www.ncbi.nlm.nih.gov/pubmed/?term=31690678
https://www.ncbi.nlm.nih.gov/pubmed/?term=26541135
https://www.ncbi.nlm.nih.gov/pubmed/?term=24556505
https://www.ncbi.nlm.nih.gov/pubmed/?term=22896687
https://www.ncbi.nlm.nih.gov/pubmed/?term=26862758
https://www.ncbi.nlm.nih.gov/pubmed/?term=32636844

Ongoing clinical trial:
https://clinicaltrials.gov/ct2/show/NCT02508376
https://clinicaltrials.gov/ct2/show/NCT02647489
https://clinicaltrials.gov/ct2/show/NCT04177355
https://clinicaltrials.gov/ct2/show/NCT03589794

**Comment by yongqunh** [comment]
Added to VO:
http://purl.obolibrary.org/obo/VO_0005421
