### ISSUE TITLE
VAC: GLA-SE

### ISSUE THREAD

**Issue by AriJoffe** [vaccineontology/VO#596]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=62

Chemical Nature: other
Mechanism of Action: TLR4; Innate Immune Activation
Immune profile induced: Th1-biased

Route of immunization: IM
Point of Contact: Christopher Fox, AAHI

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=27142329
https://www.ncbi.nlm.nih.gov/pubmed/?term=21060869
https://www.ncbi.nlm.nih.gov/pubmed/?term=20944089
https://www.ncbi.nlm.nih.gov/pubmed/?term=20944089
https://www.ncbi.nlm.nih.gov/pubmed/?term=20944089
https://www.ncbi.nlm.nih.gov/pubmed/?term=21816196
https://www.ncbi.nlm.nih.gov/pubmed/?term=21690242
https://www.ncbi.nlm.nih.gov/pubmed/?term=21060869
https://www.ncbi.nlm.nih.gov/pubmed/?term=22291184
https://www.ncbi.nlm.nih.gov/pubmed/?term=22291184
https://www.ncbi.nlm.nih.gov/pubmed/?term=23045649
https://www.ncbi.nlm.nih.gov/pubmed/?term=23045649
https://www.ncbi.nlm.nih.gov/pubmed/?term=22509423
https://www.ncbi.nlm.nih.gov/pubmed/?term=22896687
https://www.ncbi.nlm.nih.gov/pubmed/?term=23904160
https://www.ncbi.nlm.nih.gov/pubmed/?term=23954378
https://www.ncbi.nlm.nih.gov/pubmed/?term=22425788
https://www.ncbi.nlm.nih.gov/pubmed/?term=22891286
https://www.ncbi.nlm.nih.gov/pubmed/?term=22891286
https://www.ncbi.nlm.nih.gov/pubmed/?term=23624057
https://www.ncbi.nlm.nih.gov/pubmed/?term=23624057
https://www.ncbi.nlm.nih.gov/pubmed/?term=23228811
https://www.ncbi.nlm.nih.gov/pubmed/?term=25024362
https://www.ncbi.nlm.nih.gov/pubmed/?term=25030053
https://www.ncbi.nlm.nih.gov/pubmed/?term=24404140
https://www.ncbi.nlm.nih.gov/pubmed/?term=24556505
https://www.ncbi.nlm.nih.gov/pubmed/?term=24556505
https://www.ncbi.nlm.nih.gov/pubmed/?term=24397898
https://www.ncbi.nlm.nih.gov/pubmed/?term=24397898
https://www.ncbi.nlm.nih.gov/pubmed/?term=24728521
https://www.ncbi.nlm.nih.gov/pubmed/?term=24728521
https://www.ncbi.nlm.nih.gov/pubmed/?term=25367751
https://www.ncbi.nlm.nih.gov/pubmed/?term=26541135
https://www.ncbi.nlm.nih.gov/pubmed/?term=25637347
https://www.ncbi.nlm.nih.gov/pubmed/?term=27005808
https://www.ncbi.nlm.nih.gov/pubmed/?term=26656121
https://www.ncbi.nlm.nih.gov/pubmed/?term=26874325
https://www.ncbi.nlm.nih.gov/pubmed/?term=26791076
https://www.ncbi.nlm.nih.gov/pubmed/?term=27466350
https://www.ncbi.nlm.nih.gov/pubmed/?term=27699241
https://www.ncbi.nlm.nih.gov/pubmed/?term=29176865
https://www.ncbi.nlm.nih.gov/pubmed/?term=27958370
https://www.ncbi.nlm.nih.gov/pubmed/?term=29263879
https://www.ncbi.nlm.nih.gov/pubmed/?term=29795025
https://www.ncbi.nlm.nih.gov/pubmed/?term=29983563
https://www.ncbi.nlm.nih.gov/pubmed/?term=29619252
https://www.ncbi.nlm.nih.gov/pubmed/?term=29619252
https://www.ncbi.nlm.nih.gov/pubmed/?term=27895131
https://www.ncbi.nlm.nih.gov/pubmed/?term=32636844
https://www.ncbi.nlm.nih.gov/pubmed/?term=29541075
https://www.ncbi.nlm.nih.gov/pubmed/?term=33705411
https://www.ncbi.nlm.nih.gov/pubmed/?term=35126135
https://www.ncbi.nlm.nih.gov/pubmed/?term=19679214
https://www.ncbi.nlm.nih.gov/pubmed/?term=26731269
https://www.ncbi.nlm.nih.gov/pubmed/?term=26453448
https://www.ncbi.nlm.nih.gov/pubmed/?term=26453448
https://www.ncbi.nlm.nih.gov/pubmed/?term=27456709
https://www.ncbi.nlm.nih.gov/pubmed/?term=32023469
https://www.ncbi.nlm.nih.gov/pubmed/?term=32402293
https://www.ncbi.nlm.nih.gov/pubmed/?term=32348377
https://www.ncbi.nlm.nih.gov/pubmed/?term=32697993
https://www.ncbi.nlm.nih.gov/pubmed/?term=29515589
https://www.ncbi.nlm.nih.gov/pubmed/?term=33046728
https://www.ncbi.nlm.nih.gov/pubmed/?term=31690678
https://www.ncbi.nlm.nih.gov/pubmed/?term=31174937
https://www.ncbi.nlm.nih.gov/pubmed/?term=30567978
https://www.ncbi.nlm.nih.gov/pubmed/?term=31362695
https://www.ncbi.nlm.nih.gov/pubmed/?term=29769270
https://www.ncbi.nlm.nih.gov/pubmed/?term=31521953
https://www.ncbi.nlm.nih.gov/pubmed/?term=28298421

Ongoing clinical trial:
https://clinicaltrials.gov/ct2/show/NCT01484548
https://clinicaltrials.gov/ct2/show/NCT01751048
https://clinicaltrials.gov/ct2/show/NCT02071758
https://clinicaltrials.gov/ct2/show/NCT02465216
https://clinicaltrials.gov/ct2/show/NCT01927159
https://clinicaltrials.gov/ct2/show/NCT01599897
https://clinicaltrials.gov/ct2/show/NCT01154049
https://clinicaltrials.gov/ct2/show/NCT03302897
https://clinicaltrials.gov/ct2/show/NCT02465216
https://clinicaltrials.gov/ct2/show/NCT02508376
https://clinicaltrials.gov/ct2/show/NCT03806686
https://clinicaltrials.gov/ct2/show/NCT01949909
https://clinicaltrials.gov/ct2/show/NCT01540474
https://clinicaltrials.gov/ct2/show/NCT02014727
https://clinicaltrials.gov/ct2/show/NCT02647489
https://clinicaltrials.gov/ct2/show/NCT02658253
https://clinicaltrials.gov/ct2/show/NCT01991561
https://clinicaltrials.gov/ct2/show/NCT01596725
https://clinicaltrials.gov/ct2/show/NCT01147068
https://clinicaltrials.gov/ct2/show/NCT03820414
https://clinicaltrials.gov/ct2/show/NCT03220724
https://clinicaltrials.gov/ct2/show/NCT03409276
https://clinicaltrials.gov/ct2/show/NCT01864876
https://clinicaltrials.gov/ct2/show/NCT02115815
https://clinicaltrials.gov/ct2/show/NCT01397604

**Comment by yongqunh** [comment]
Added to VO:
http://purl.obolibrary.org/obo/VO_0005420
