### ISSUE TITLE
VAC: MicroCrystalline Tyrosine (MCT)

### ISSUE THREAD

**Issue by AriJoffe** [vaccineontology/VO#597]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=25

Chemical Nature: other
Mechanism of Action: Activation of APCs, activation of T cells and stimulating B cell proliferation (IgG)
Immune profile induced: Th1-biased

Route of immunization: IM and SQ
Point of Contact: Matthew Heath, Allergy Therapeutics (UK) Ltd

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=29592962
https://www.ncbi.nlm.nih.gov/pubmed/?term=28347293
https://www.ncbi.nlm.nih.gov/pubmed/?term=28468322
https://www.ncbi.nlm.nih.gov/pubmed/?term=28953265

Ongoing clinical trial: n/a

**Comment by yongqunh** [comment]
Added:
http://purl.obolibrary.org/obo/VO_0005270
by Ani Bernardi and Oliver He
