### ISSUE TITLE
VAC: ProLNG-S

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#605]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=34

Chemical Nature: small molecule
Mechanism of Action: Innate Immune Activation
Immune profile induced: Th1-biased

Route of immunization: SQ
Point of Contact: Taegyan Kang, Progeneer

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=36635335

Ongoing clinical trials: n/a

**Comment by yongqunh** [comment]
VO ID assigned: VO_0005472
http://purl.obolibrary.org/obo/VO_0005472
