### ISSUE TITLE
VAC: NanoAlum

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#608]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=71

Chemical Nature: Small molecule
Mechanism of Action: Innate Immune Activation
Immune profile induced: Th1-biased

Route of immunization: IM
Point of Contact: Valerie Soza, AAHI

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=30622742
https://www.ncbi.nlm.nih.gov/pubmed/?term=31930264

Ongoing clinical trials: n/a

**Comment by yongqunh** [comment]
VO assigned: VO_0005475

http://purl.obolibrary.org/obo/VO_0005475
