### ISSUE TITLE
VAC: Nanostructured Lipid Carrier (NLC)

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#609]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=71

Chemical Nature: Small molecule
Mechanism of Action: Innate Immune Activation
Immune profile induced: Th1-biased

Route of immunization: IM
Point of Contact: Valerie Soza, AAHI

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=35911728
https://www.ncbi.nlm.nih.gov/pubmed/?term=24551202
https://www.ncbi.nlm.nih.gov/pubmed/?term=34058388
https://www.ncbi.nlm.nih.gov/pubmed/?term=35308783
https://www.ncbi.nlm.nih.gov/pubmed/?term=36589712
https://www.ncbi.nlm.nih.gov/pubmed/?term=36323666

Ongoing clinical trials: 
https://clinicaltrials.gov/ct2/show/NCT05370040

**Comment by yongqunh** [comment]
Is this NanoAlum? 
https://vac.niaid.nih.gov/view?id=71 
?

**Comment by yongqunh** [comment]
This appears to be VAC ID 70:
https://vac.niaid.nih.gov/view?id=70
I will make VO id based on this.

**Comment by yongqunh** [comment]
VO ID assigned: VO_0005476
http://purl.obolibrary.org/obo/VO_0005476
