### ISSUE TITLE
VAC: SLA-AF

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#610]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=71

Chemical Nature: Small molecule
Mechanism of Action: Innate Immune Activation
Immune profile induced: n/a

Route of immunization: IM
Point of Contact: Valerie Soza, AAHI

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=32983577
https://www.ncbi.nlm.nih.gov/pubmed/?term=35459225

Ongoing clinical trials: n/a

**Comment by yongqunh** [comment]
The VAC ID should be 72:
https://vac.niaid.nih.gov/view?id=72

**Comment by yongqunh** [comment]
VO ID assigned: VO_0005482 
http://purl.obolibrary.org/obo/VO_0005482
