### ISSUE TITLE
VAC: LMQ

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#614]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=78

Chemical Nature: Combination adjuvant
Mechanism of Action: n/a
Immune profile induced: Th1-biased

Route of immunization: IM
Point of Contact: Maria Lawrenz, Vaccine Formulation Institute

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=36634821
https://www.ncbi.nlm.nih.gov/pubmed/?term=36119058
https://www.ncbi.nlm.nih.gov/pubmed/?term=37029167

Ongoing clinical trials:
n/a

**Comment by zhengj2007** [comment]
Hi @nkosar I am working on the term you submitted. Here is the definition I made based on the information your provided:
A combination vaccine adjuvant that induced a Th1-biased immune response.

Could you please review it and improve the definition if needed? Thanks!

**Comment by nkosar** [comment]
@zhengj2007 hi, for this adjuvant you can use the definition "liposome-based combination adjuvant of a synthetic TLR agonist and saponin"

**Comment by zhengj2007** [comment]
Thanks @nkosar
