### ISSUE TITLE
VAC: SMNP

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#632]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=77

Chemical Nature: Combination adjuvant
Mechanism of Action: Cytokine induction in draining lymph nodes with increased lymph flow and lymph antigen accumulation
Immune profile induced: Mixed Th1/Th2

Route of immunization: s.c. / i.m. / i.n.
Point of Contact: Katarzyna Kaczmarek Michaels, Massachusetts Institute of Technology

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=34860581
https://www.ncbi.nlm.nih.gov/pubmed/?term=36131022
https://www.ncbi.nlm.nih.gov/pubmed/?term=34878851

Ongoing clinical trials:
n/a

**Comment by zhengj2007** [comment]
Hi @nkosar, I am working on the term you submitted. Could you please add the definition? Thanks!

**Comment by nkosar** [comment]
@zhengj2007 definition would be " AS01-mimic, Immune Stimulating Complex (ISCOM) with a TLR4 agonist"

**Comment by zhengj2007** [comment]
Added in VO, with ID: VO_0006095
