### ISSUE TITLE
VAC: ALFQ

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#633]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=79

Chemical Nature: 
• Natural compound
• Synthetic derivative of natural compound
• Combination adjuvant
Mechanism of Action: MPLA: TLR4 agonist QS21: Sugar-lawn likely recog. by lectins to facilitate uptake by MΏ, DCs, etc
Immune profile induced: Mixed Th1/Th2

Route of immunization: ID, IM
Point of Contact: Mangala Rao, Walter Reed Army Institute of Research

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=34202178
https://www.ncbi.nlm.nih.gov/pubmed/?term=31827000
https://www.ncbi.nlm.nih.gov/pubmed/?term=34470866
https://www.ncbi.nlm.nih.gov/pubmed/?term=35632473
https://www.ncbi.nlm.nih.gov/pubmed/?term=36417525
https://www.ncbi.nlm.nih.gov/pubmed/?term=34914540
https://www.ncbi.nlm.nih.gov/pubmed/?term=32881968
https://www.ncbi.nlm.nih.gov/pubmed/?term=26372857
https://www.ncbi.nlm.nih.gov/pubmed/?term=36055874
https://www.ncbi.nlm.nih.gov/pubmed/?term=34202178
https://www.ncbi.nlm.nih.gov/pubmed/?term=36679887
https://www.ncbi.nlm.nih.gov/pubmed/?term=36934088
https://www.ncbi.nlm.nih.gov/pubmed/?term=34903722
https://www.ncbi.nlm.nih.gov/pubmed/?term=31775762
https://www.ncbi.nlm.nih.gov/pubmed/?term=28596090
https://www.ncbi.nlm.nih.gov/pubmed/?term=31151801
https://www.ncbi.nlm.nih.gov/pubmed/?term=34711815
https://www.ncbi.nlm.nih.gov/pubmed/?term=34159328

Ongoing clinical trials:
https://clinicaltrials.gov/ct2/show/NCT04268420
https://clinicaltrials.gov/ct2/show/NCT04296279
https://clinicaltrials.gov/ct2/show/NCT04784767
https://clinicaltrials.gov/ct2/show/NCT05500417
https://clinicaltrials.gov/ct2/show/NCT04826094
https://clinicaltrials.gov/ct2/show/NCT04658667
https://clinicaltrials.gov/ct2/show/NCT05423418

**Comment by zhengj2007** [comment]
Hi @nkosar, I am working on the term you submitted. Could you please add the definition? Thanks!

**Comment by nkosar** [comment]
@zhengj2007 you can use "AS01-mimic, liposomal combination adjuvant of a TLR4 agonist and saponin" as the definition

**Comment by zhengj2007** [comment]
Added in VO, with ID: VO_0006096
