### ISSUE TITLE
inconsistent issues

### ISSUE THREAD

**Issue by zhengj2007** [vaccineontology/VO#637]
[Ad5-nCoV](http://purl.obolibrary.org/obo/VO_0005144)
'induced by vaccination of' some 'vaccine-induced T cell interferon-gamma production'
- The range of 'induced by vaccination of' should be a vaccine, not a process,  'vaccine-induced T cell interferon-gamma production'

[Oxford–AstraZeneca COVID-19 vaccine](http://purl.obolibrary.org/obo/VO_0005158)
'induced by vaccination of' some 'vaccine-induced antiviral neutralizing antibody response'
- The range of 'induced by vaccination of' should be a vaccine, not a process,  'vaccine-induced antiviral neutralizing antibody response'

[Tevax vaccine](http://purl.obolibrary.org/obo/VO_0005438)
'has role' some 'bacterial vaccine'
- The range of 'has role' should be a role, not material entity, 'bacterial vaccine'

**Comment by Huffmaar** [comment]
[Ad5-nCoV](http://purl.obolibrary.org/obo/VO_0005144)
'induced by vaccination of' some 'vaccine-induced T cell interferon-gamma production'

    The range of 'induced by vaccination of' should be a vaccine, not a process, 'vaccine-induced T cell interferon-gamma production'

[Oxford–AstraZeneca COVID-19 vaccine](http://purl.obolibrary.org/obo/VO_0005158)
'induced by vaccination of' some 'vaccine-induced antiviral neutralizing antibody response'

    The range of 'induced by vaccination of' should be a vaccine, not a process, 'vaccine-induced antiviral neutralizing antibody response'

-- Removed range for 'induced by vaccination of'; this may cause some further issue if domain is set to vaccine (some terms use this for its inverse) -- issue will be raised further.

[Tevax vaccine](http://purl.obolibrary.org/obo/VO_0005438)
'has role' some 'bacterial vaccine'

    The range of 'has role' should be a role, not material entity, 'bacterial vaccine'

-- Removed 'has role' entry as 'bacterial vaccine' should be inferred by parent.

**Comment by zhengj2007** [comment]
All issues resolved
