### ISSUE TITLE
VO terms with multiple labels

### ISSUE THREAD

**Issue by zhengj2007** [vaccineontology/VO#640]
ID | Label
-- | --
VO:0000902 | PROTEQ-FLU (European Union)
VO:0000902 | Recombitek (United States)
VO:0001020 | Advent
VO:0001020 | Coccivac
VO:0001020 | Immucox
VO:0001020 | Nobilis Cox ATM
VO:0001020 | Paracox
VO:0001082 | AcMNPV vector
VO:0001082 | autographa californica multicapsid Nucleopolyhedrovirus vaccine vector
VO:0010058 | Plasmodium knowlesi CSP
VO:0010058 | Plasmodium knowlesi PkCSP
VO:0010059 | Plasmodium knowlesi PkSSP2
VO:0010059 | Plasmodium knowlesi SSP2
VO:0010060 | Plasmodium knowlesi AMA1
VO:0010060 | Plasmodium knowlesi PkAMA1
VO:0010061 | Plasmodium knowlesi MSP1
VO:0010061 | Plasmodium knowlesi PkMSP1p42
VO:0010062 | Plasmodium vivax CelTOS
VO:0010062 | Plasmodium vivax PvCelTOS
VO:0010063 | Plasmodium vivax CS
VO:0010063 | Plasmodium vivax PvCS

Some might be same vaccine, need choose one as label, the other added as alternative label.

@Huffmaar It seems some of the terms are parasite vaccines. Could you please check it?

**Comment by zhengj2007** [comment]
Some terms with label in English and literal. We may decide which one we prefer.

ID | Label
-- | --
VO:0001818 | VIOLIN vaccine ID
VO:0001818 | VIOLIN vaccine ID@en
VO:0003099 | trade name
VO:0003099 | trade name@en
VO:0003146 | has vaccine active ingredient
VO:0003146 | has vaccine active ingredient@en
VO:0003147 | has vaccine ingredient
VO:0003147 | has vaccine ingredient@en
VO:0003151 | vaccine dose annotation
VO:0003151 | vaccine dose annotation@en
VO:0003158 | vaccine proper name
VO:0003158 | vaccine proper name@en
VO:0003159 | manufacturer
VO:0003159 | manufacturer@en
VO:0003160 | FDA vaccine indications
VO:0003160 | FDA vaccine indications@en
VO:0003161 | vaccine package insert PDF URL
VO:0003161 | vaccine package insert PDF URL@en
VO:0003198 | RxNORM ID
VO:0003198 | RxNORM ID@en
VO:0003557 | has Protegen id
VO:0003557 | has Protegen id@en
VO:0003558 | has Protegen annotation
VO:0003558 | has Protegen annotation@en
VO:0003560 | RxNORM Preferred Name
VO:0003560 | RxNORM Preferred Name@en

**Comment by Huffmaar** [comment]
1. Those look to be a case of ontorat using different names from an update; my preference is for the terms with Pv[Gene] or pk[Gene] to be alternative labels instead of removing.
2. I do not have a strong preference, but I would want to see how many use @en for the default name scheme.

**Comment by Huffmaar** [comment]
The preferred name for each one is shown below.

<html><body>

VO:0000902 | PROTEQ-FLU (European Union)
-- | --
VO:0001082 | autographa californica multicapsid Nucleopolyhedrovirus vaccine vector
VO:0010058 | Plasmodium knowlesi CSP
VO:0010059 | Plasmodium knowlesi SSP2
VO:0010060 | Plasmodium knowlesi AMA1
VO:0010061 | Plasmodium knowlesi MSP1
VO:0010062 | Plasmodium vivax CelTOS
VO:0010063 | Plasmodium vivax CS

</body>
</html>


For the following terms, make the following terms alternative label: 


<html><body>

VO:0000902 | PROTEQ-FLU (European Union)
-- | --
VO:0001082 | autographa californica multicapsid Nucleopolyhedrovirus vaccine vector

</body>
</html>


For the second table, for remove the preferred names that use @En.

I need read up more for Coccidocis vaccines that share the label.
Axiom-wise they seem to be the same. 
I am leaning to having these be alternative labels; I'm not sure what the primary name should be.
VO:0001020 | Advent
VO:0001020 | Coccivac
VO:0001020 | Immucox
VO:0001020 | Nobilis Cox ATM
VO:0001020 | Paracox

**Comment by zhengj2007** [comment]
All issues resolved
