### ISSUE TITLE
Duplicated labels

### ISSUE THREAD

**Issue by zhengj2007** [vaccineontology/VO#643]
The label used for more than one terms. Some might be the same term, need to merge. If not, may need to relabel the term.

ID | Label
-- | --
VO:0002944 | Yersinia pestis smpB/ssrA mutant vaccine
VO:0002945 | Yersinia pestis smpB/ssrA mutant vaccine
VO:0002939 | Yersinia pestis guaBA mutant vaccine
VO:0002940 | Yersinia pestis guaBA mutant vaccine
VO:0003002 | Western equine encephalomyelitis virus PE2/E2 mutant virus
VO:0003004 | Western equine encephalomyelitis virus PE2/E2 mutant virus
VO:0003000 | Western equine encephalomyelitis virus PE2/E1 mutant vaccine
VO:0003003 | Western equine encephalomyelitis virus PE2/E1 mutant vaccine
VO:0003001 | WEEV Subunit E2 Protein Vaccine
VO:0011506 | WEEV Subunit E2 Protein Vaccine
VO:0002999 | WEEV DNA Vaccine encoding 6K-E1 Protein
VO:0011505 | WEEV DNA Vaccine encoding 6K-E1 Protein
VO:0011226 | VP7
VO:0011256 | VP7
VO:0011222 | VP6
VO:0011257 | VP6
VO:0011258 | VP6
VO:0011227 | VP4
VO:0011244 | VP4
VO:0011255 | VP4
VO:0011054 | VP2
VO:0011254 | VP2
VO:0002682 | virG from Shigella
VO:0002683 | virG from Shigella
VO:0002996 | VEE Virus PE2/E1 mutant vaccine
VO:0002997 | VEE Virus PE2/E1 mutant vaccine
VO:0011041 | US6
VO:0011096 | US6
VO:0011240 | US6
VO:0011043 | UL44
VO:0011103 | UL44
VO:0011239 | UL44
VO:0011273 | TSA
VO:0011338 | TSA
VO:0003014 | Toxoplasma gondii OMPDC/UP mutant vaccine
VO:0003015 | Toxoplasma gondii OMPDC/UP mutant vaccine
VO:0001831 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.29)
VO:0002192 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.29)
VO:0001830 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.26)
VO:0002191 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.26)
VO:0001829 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.24)
VO:0002190 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.24)
VO:0001828 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.23)
VO:0002189 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.23)
VO:0001827 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.22)
VO:0002188 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.22)
VO:0001826 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.12)
VO:0002187 | Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.12)
VO:0002610 | siaD from Neisseria meningitidis
VO:0002611 | siaD from Neisseria meningitidis
VO:0002927 | Shigella sonnei virG/senA/senB/msbB2 mutant vaccine
VO:0002929 | Shigella sonnei virG/senA/senB/msbB2 mutant vaccine
VO:0002931 | Shigella sonnei virG/senA/senB/msbB2 mutant vaccine
VO:0002933 | Shigella sonnei virG/senA/senB/msbB2 mutant vaccine
VO:0002928 | Shigella sonnei virG/senA/senB mutant vaccine
VO:0002930 | Shigella sonnei virG/senA/senB mutant vaccine
VO:0002932 | Shigella sonnei virG/senA/senB mutant vaccine
VO:0002680 | senB from Shigella
VO:0002681 | senB from Shigella
VO:0002678 | senA from Shigella
VO:0002679 | senA from Shigella
VO:0000663 | SC602
VO:0002926 | SC602
VO:0002915 | Salmonella Typhimurium znuABC mutant vaccine
VO:0002916 | Salmonella Typhimurium znuABC mutant vaccine
VO:0002917 | Salmonella Typhimurium znuABC mutant vaccine
VO:0002897 | Salmonella Typhimurium IppB/msbB mutant vaccine
VO:0002899 | Salmonella Typhimurium IppB/msbB mutant vaccine
VO:0002895 | Salmonella Typhimurium IppA/IppB/msbB
VO:0002896 | Salmonella Typhimurium IppA/IppB/msbB
VO:0002898 | Salmonella Typhimurium IppA/IppB/msbB
VO:0002876 | Salmonella Typhimurium gyrA/cpxA/rpoB mutant vaccine
VO:0002891 | Salmonella Typhimurium gyrA/cpxA/rpoB mutant vaccine
VO:0002907 | Salmonella Typhimurium gyrA/cpxA/rpoB mutant vaccine
VO:0002874 | Salmonella Typhimurium guaBA/clpP/fliD mutant vaccine
VO:0002882 | Salmonella Typhimurium guaBA/clpP/fliD mutant vaccine
VO:0002886 | Salmonella Typhimurium guaBA/clpP/fliD mutant vaccine
VO:0002888 | Salmonella Typhimurium guaBA/clpP/fliD mutant vaccine
VO:0002873 | Salmonella Typhimurium guaBA/clpP mutant vaccine
VO:0002885 | Salmonella Typhimurium guaBA/clpP mutant vaccine
VO:0002887 | Salmonella Typhimurium guaBA/clpP mutant vaccine
VO:0002878 | Salmonella Typhimurium cya/crp mutant vaccine
VO:0002880 | Salmonella Typhimurium cya/crp mutant vaccine
VO:0002868 | Salmonella Typhimurium asd/rfc mutant vaccine
VO:0002906 | Salmonella Typhimurium asd/rfc mutant vaccine
VO:0002905 | Salmonella Gallinarum relA/spoT mutant vaccine
VO:0002910 | Salmonella Gallinarum relA/spoT mutant vaccine
VO:0002877 | Salmonella Gallinarum cpxR/Ion mutant vaccine
VO:0002894 | Salmonella Gallinarum cpxR/Ion mutant vaccine
VO:0002870 | Salmonella Gallinarum cbiA/cobS mutant vaccine
VO:0002875 | Salmonella Gallinarum cbiA/cobS mutant vaccine
VO:0002871 | Salmonella Enteritidis guaBA/clpP mutant vaccine
VO:0002884 | Salmonella Enteritidis guaBA/clpP mutant vaccine
VO:0002890 | Salmonella Enteritidis guaBA/clpP mutant vaccine
VO:0002881 | Salmonella enterica fliC/guaB mutant vaccine
VO:0002889 | Salmonella enterica fliC/guaB mutant vaccine
VO:0011000 | SAG1
VO:0011253 | SAG1
VO:0000678 | S. sonnei strain WRSS1
VO:0002921 | S. sonnei strain WRSS1
VO:0000676 | S. dysenteriae 1 strain WRSd1
VO:0002919 | S. dysenteriae 1 strain WRSd1
VO:0004664 | rMVA-SIV-CD40L
VO:0004792 | rMVA-SIV-CD40L
VO:0000431 | rLm/iglC
VO:0011347 | rLm/iglC
VO:0002986 | Pseudorabies virus gp50/gp63 mutant vaccine
VO:0002987 | Pseudorabies virus gp50/gp63 mutant vaccine
VO:0002983 | Pseudorabies virus glycoprotein E/G/UL23 mutant vaccine
VO:0002984 | Pseudorabies virus glycoprotein E/G/UL23 mutant vaccine
VO:0002988 | Pseudorabies virus glycoprotein E/G/UL23 mutant vaccine
VO:0011146 | PrM
VO:0011179 | PrM
VO:0011315 | PrM
VO:0001825 | Porcine Circovirus Type 2, Killed Baculovirus Vector Vaccine (USDA: 19K5.R0)
VO:0002194 | Porcine Circovirus Type 2, Killed Baculovirus Vector Vaccine (USDA: 19K5.R0)
VO:0002753 | PE2 from Western equine encephalomyelitis virus
VO:0002754 | PE2 from Western equine encephalomyelitis virus
VO:0000026 | pCMV4 DNA vaccine plasmid@en
VO:0000217 | pCMV4 DNA vaccine plasmid@en
VO:0002538 | panD from Mycobacterium tuberculosis
VO:0002539 | panD from Mycobacterium tuberculosis
VO:0002536 | panC from Mycobacterium tuberculosis
VO:0002537 | panC from Mycobacterium tuberculosis
VO:0010914 | P4
VO:0011288 | P4
VO:0010930 | P1
VO:0011180 | P1
VO:0003009 | P. yoelii p36/p52 mutant vaccine
VO:0003010 | P. yoelii p36/p52 mutant vaccine
VO:0004209 | Ovine Ecthyma Live Virus Vaccine
VO:0004210 | Ovine Ecthyma Live Virus Vaccine
VO:0002763 | OMPDC from Toxoplasma gondii
VO:0002764 | OMPDC from Toxoplasma gondii
VO:0011147 | NS1
VO:0011312 | NS1
VO:0000779 | NP-VRP
VO:0011387 | NP-VRP
VO:0002859 | Neisseria meningitidis rfaF/siaD mutant vaccine
VO:0002861 | Neisseria meningitidis rfaF/siaD mutant vaccine
VO:0002858 | Neisseria meningitidis metH/siaD mutant vaccine
VO:0002860 | Neisseria meningitidis metH/siaD mutant vaccine
VO:0002648 | msbB from Salmonella spp.
VO:0002649 | msbB from Salmonella spp.
OBI:0000835 | manufacturer
VO:0003159 | manufacturer
VO:0000564 | M. tuberculosis secA2 mutant
VO:0002794 | M. tuberculosis secA2 mutant
VO:0000588 | M. tuberculosis phoP mutant SO2
VO:0002790 | M. tuberculosis phoP mutant SO2
VO:0002646 | lppB from Salmonella spp.
VO:0002647 | lppB from Salmonella spp.
VO:0002777 | Listeria monocytogenes actA/plcB mutant vaccine
VO:0002778 | Listeria monocytogenes actA/plcB mutant vaccine
VO:0000307 | KKF24
VO:0002848 | KKF24
VO:0010988 | IroN
VO:0010997 | IroN
VO:0002675 | icsA/virG from Shigella
VO:0002676 | icsA/virG from Shigella
VO:0010934 | HspB
VO:0012378 | HspB
VO:0002975 | Herpes simplex virus type 1 DNA vaccine encoding GE
VO:0011423 | Herpes simplex virus type 1 DNA vaccine encoding GE
VO:0010916 | Hap from H. influenzae
VO:0010917 | Hap from H. influenzae
VO:0002637 | guaB from Salmonella spp.
VO:0002638 | guaB from Salmonella spp.
VO:0002639 | guaB from Salmonella spp.
VO:0002640 | guaB from Salmonella spp.
VO:0002634 | guaA from Salmonella spp.
VO:0002635 | guaA from Salmonella spp.
VO:0002636 | guaA from Salmonella spp.
VO:0010998 | GroEL
VO:0011075 | GroEL
VO:0010910 | GP from Zaire ebolavirus
VO:0010932 | GP from Zaire ebolavirus
VO:0011109 | G glycoprotein
VO:0011310 | G glycoprotein
VO:0011313 | G glycoprotein
VO:0002849 | Francisella tularensis purMCD mutant vaccine
VO:0002851 | Francisella tularensis purMCD mutant vaccine
VO:0002964 | Feline infectious peritonitis virus 7ab mutant vaccine
VO:0002965 | Feline infectious peritonitis virus 7ab mutant vaccine
VO:0002961 | Feline infectiour peritonitis virus 3abc mutant vaccine
VO:0002962 | Feline infectiour peritonitis virus 3abc mutant vaccine
VO:0002963 | Feline infectiour peritonitis virus 3abc mutant vaccine
VO:0011167 | F fusion protein
VO:0011208 | F fusion protein
VO:0011314 | F fusion protein
VO:0002831 | Edwardsiella tarda aroC/slyA mutant vaccine
VO:0002835 | Edwardsiella tarda aroC/slyA mutant vaccine
VO:0002832 | Edwardsiella tarda aroC/esrC mutant vaccine
VO:0002834 | Edwardsiella tarda aroC/esrC mutant vaccine
VO:0002751 | E2 from Western equine encephalomyelitis virus
VO:0002752 | E2 from Western equine encephalomyelitis virus
VO:0010897 | E2
VO:0011305 | E2
VO:0002749 | E1 from Western equine encephalomyelitis virus
VO:0002750 | E1 from Western equine encephalomyelitis virus
VO:0011177 | E protein
VO:0011311 | E protein
VO:0010882 | DnaK
VO:0010970 | DnaK
VO:0012408 | DnaK
VO:0000733 | CVD 1204(pGA1-CS2)
VO:0002918 | CVD 1204(pGA1-CS2)
VO:0002628 | crp from Salmonella spp.
VO:0002629 | crp from Salmonella spp.
VO:0002621 | clpP from Salmonella spp.
VO:0002622 | clpP from Salmonella spp.
VO:0002623 | clpP from Salmonella spp.
VO:0002624 | clpP from Salmonella spp.
VO:0005228 | ChAdV68-S@en
VO:0005394 | ChAdV68-S@en
VO:0007358 | CD80 Breast Cancer Vaccine
VO:0007592 | CD80 Breast Cancer Vaccine
VO:0002803 | Bordetella bronchiseptica bscN and cyaA double mutant vaccine
VO:0002804 | Bordetella bronchiseptica bscN and cyaA double mutant vaccine
VO:0002802 | Bordetella bronchiseptica aroA/trpE mutant vaccine
VO:0002806 | Bordetella bronchiseptica aroA/trpE mutant vaccine
VO:0007328 | Bcl-Xs Adenovirus Vaccine
VO:0007589 | Bcl-Xs Adenovirus Vaccine
VO:0002820 | B. melitensis WR201 (16MŒîpurEK)
VO:0002821 | B. melitensis WR201 (16MŒîpurEK)
VO:0002810 | B. abortus and B. melitensis mutants with unmarked deletion of asp24, virB2, or manBA
VO:0002814 | B. abortus and B. melitensis mutants with unmarked deletion of asp24, virB2, or manBA
VO:0002822 | B. abortus and B. melitensis mutants with unmarked deletion of asp24, virB2, or manBA
VO:0007301 | Autologous Immunoglobulin Idiotype-KLH Conjugate Vaccine
VO:0007579 | Autologous Immunoglobulin Idiotype-KLH Conjugate Vaccine
VO:0007289 | Autologous Dendritic Cell-Tumor Fusion Vaccine
VO:0007577 | Autologous Dendritic Cell-Tumor Fusion Vaccine
VO:0007283 | Autologous Dendritic Cell Vaccine ACT2001
VO:0007576 | Autologous Dendritic Cell Vaccine ACT2001
VO:0002617 | asd from Salmonella spp.
VO:0002618 | asd from Salmonella spp.
VO:0002672 | aroD from Shigella
VO:0002673 | aroD from Shigella
VO:0002614 | aroC from Salmonella spp.
VO:0002615 | aroC from Salmonella spp.
VO:0002580 | aroC from Edwardsiella tarda
VO:0002581 | aroC from Edwardsiella tarda
VO:0002582 | aroC from Edwardsiella tarda
VO:0002668 | aroA from Shigella
VO:0002669 | aroA from Shigella
VO:0002670 | aroA from Shigella
VO:0002671 | aroA from Shigella
VO:0002551 | aroA from Bordetella bronchiseptica
VO:0002552 | aroA from Bordetella bronchiseptica
VO:0002864 | Aro-deleted S. Typhi
VO:0002866 | Aro-deleted S. Typhi
VO:0002519 | apxIIC from Actinobacillus pleuropneumoniae
VO:0002520 | apxIIC from Actinobacillus pleuropneumoniae
VO:0002768 | Actinobacillus pleuropneumoniae ureC and apxIIA double mutant deletion vaccine
VO:0002774 | Actinobacillus pleuropneumoniae ureC and apxIIA double mutant deletion vaccine
VO:0002771 | Actinobacillus pleuropneumoniae apxIIIB and apxIIID double mutant vaccine
VO:0002772 | Actinobacillus pleuropneumoniae apxIIIB and apxIIID double mutant vaccine
VO:0002769 | Actinobacillus pleuropneumoniae apxIIC and apxIVA double deletion mutant vaccine
VO:0002773 | Actinobacillus pleuropneumoniae apxIIC and apxIVA double deletion mutant vaccine
VO:0002526 | actA from Listeria monocytogenes
VO:0002527 | actA from Listeria monocytogenes
VO:0002800 | A. salmonicida live-attenuated vaccine encoding AroA
VO:0011386 | A. salmonicida live-attenuated vaccine encoding AroA
VO:0002770 | A. pleuropneumoniae HS93C-Ampr
VO:0011385 | A. pleuropneumoniae HS93C-Ampr
VO:0003272 | 0.65 ML Varicella-Zoster Virus Vaccine Live (Oka-Merck) strain 29800 UNT/ML Injection@en
VO:0003280 | 0.65 ML Varicella-Zoster Virus Vaccine Live (Oka-Merck) strain 29800 UNT/ML Injection@en

**Comment by EllenXMZhang** [comment]
VO_0003009 P. yoelii p36/p52 mutant vaccine
VO_0003010 P. yoelii p36/p52 mutant vaccine
VO_0003014 Toxoplasma gondii OMPDC/UP mutant vaccine
VO_0003015 Toxoplasma gondii OMPDC/UP mutant vaccine
VO_0004602 T. gondii recombinant vaccine vector rBCGpMV361-TgCyP
VO_0004656 rBCGpMV361-TgCyP
VO_0005808 PfSPZ
VO_0004910 PfSPZ Vaccine
VO_0001751 Neospora Canium Killed Protozoa Vaccine (USDA: 1N11.00)
VO_0005800 N. Canium Killed Protozoa Vaccine

**Comment by zhengj2007** [comment]
Following terms are same, merged.

Label | Keep | Deprecated
--|--|--
Autologous Dendritic Cell Vaccine ACT2001 | VO:0007283 | VO:0007576
Autologous Dendritic Cell-Tumor Fusion Vaccine | VO:0007289 | VO:0007577
Autologous Immunoglobulin Idiotype-KLH Conjugate Vaccine | VO:0007301 | VO:0007579
Bcl-Xs Adenovirus Vaccine | VO:0007328 | VO:0007589
CD80 Breast Cancer Vaccine | VO:0007358 | VO:0007592

**Comment by zhengj2007** [comment]
Following terms are duplicated based on term labels and comments. Duplicated terms are merged and the VO IDs that will not be used any more were deprecated.

label | Keep ID | Deprecated ID | Notes
-- | -- | -- | --
pCMV4 DNA vaccine plasmid | VO_0000026 | VO_0000217 | merged to Keep ID
West Nile virus gene | VO_0001448 | VO_0000197 | merged to Keep ID
KKF24 | VO_0000307 | VO_0002848 | merged to Keep ID
rLm/iglC | VO_0000431 | VO_0011347 | merged to Keep ID
M. tuberculosis phoP mutant SO2 | VO_0000588 | VO_0002790 | merged to Keep ID
S. dysenteriae 1 strain WRSd1 | VO_0000676 | VO_0002919 | merged to Keep ID
S. sonnei strain WRSS1 | VO_0000678 | VO_0002921 | merged to Keep ID
NP-VRP | VO_0011387 | VO_0000779 | merged to Keep ID
E. coli CS3 in PLGA microspheres | VO_0000933 | VO_0004262 | merged to Keep ID
avian influenza vaccine | VO_0000461 | VO_0000986 | merged to Keep ID
Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.24) | VO_0001829 | VO_0002190 | merged to Keep ID
Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.26) | VO_0001830 | VO_0002191 | merged to Keep ID
Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.29) | VO_0001831 | VO_0002192 | merged to Keep ID
Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.12) | VO_0001826 | VO_0002187 | merged to Keep ID
Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.22) | VO_0001827 | VO_0002188 | merged to Keep ID
Swine Influenza H1N1 & H3N2, Killed Virus Vaccine (USDA: 19A5.23) | VO_0001828 | VO_0002189 | merged to Keep ID
Porcine Circovirus Type 2, Killed Baculovirus Vector Vaccine (USDA: 19K5.R0) | VO_0001825 | VO_0002194 | merged to Keep ID
apxIIC from Actinobacillus pleuropneumoniae | VO_0002519 | VO_0002520 | merged to Keep ID
actA from Listeria monocytogenes | VO_0002526 | VO_0002527 | merged to Keep ID
panC from Mycobacterium tuberculosis | VO_0002536 | VO_0002537 | merged to Keep ID
panD from Mycobacterium tuberculosis | VO_0002538 | VO_0002539 | merged to Keep ID
aroA from Bordetella bronchiseptica | VO_0002551 | VO_0002552 | merged to Keep ID
aroC from Edwardsiella tarda | VO_0002580 | VO_0002581\|VO_0002582 | merged to Keep ID
siaD from Neisseria meningitidis | VO_0002610 | VO_0002611 | merged to Keep ID
aroC from Salmonella spp. | VO_0002614 | VO_0002615 | merged to Keep ID
asd from Salmonella spp. | VO_0002617 | VO_0002618 | merged to Keep ID
clpP from Salmonella spp. | VO_0002622 | VO_0002623\|VO_0002624 | merged to Keep ID
guaA from Salmonella spp. | VO_0002635 | VO_0002636 | merged to Keep ID
guaB from Salmonella spp. | VO_0002637 | VO_0002638 | merged to Keep ID
guaB from Salmonella spp. | VO_0002634\|VO_0002639 | VO_0002640 | merged to Keep ID
lppB from Salmonella spp. | VO_0002646 | VO_0002647 | merged to Keep ID
msbB from Salmonella spp. | VO_0002648 | VO_0002649 | merged to Keep ID
aroA from Shigella | VO_0002668 | VO_0002669\|VO_0002670\|VO_0002671 | merged to Keep ID
aroD from Shigella | VO_0002672 | VO_0002673 | merged to Keep ID
icsA/virG from Shigella | VO_0002675 | VO_0002676 | merged to Keep ID
senA from Shigella | VO_0002678 | VO_0002679 | merged to Keep ID
senB from Shigella | VO_0002680 | VO_0002681 | merged to Keep ID
virG from Shigella | VO_0002682 | VO_0002683 | merged to Keep ID
E1 from Western equine encephalomyelitis virus | VO_0002749 | VO_0002750 | merged to Keep ID
E2 from Western equine encephalomyelitis virus | VO_0002751 | VO_0002752 | merged to Keep ID
PE2 from Western equine encephalomyelitis virus | VO_0002753 | VO_0002754 | merged to Keep ID
OMPDC from Toxoplasma gondii | VO_0002763 | VO_0002764 | merged to Keep ID
Actinobacillus pleuropneumoniae ureC and apxIIA double mutant deletion vaccine | VO_0002768 | VO_0002774 | merged to Keep ID
Actinobacillus pleuropneumoniae apxIIC and apxIVA double deletion mutant vaccine | VO_0002769 | VO_0002773 | merged to Keep ID
A. pleuropneumoniae HS93C-Ampr | VO_0011385 | VO_0002770 | merged to Keep ID
Actinobacillus pleuropneumoniae apxIIIB and apxIIID double mutant vaccine | VO_0002771 | VO_0002772 | merged to Keep ID
Listeria monocytogenes actA/plcB mutant vaccine | VO_0002777 | VO_0002778 | merged to Keep ID
M. tuberculosis secA2 mutant | VO_0000564 | VO_0002794 | merged to Keep ID
A. salmonicida live-attenuated vaccine encoding AroA | VO_0011386 | VO_0002800 | merged to Keep ID
Bordetella bronchiseptica aroA/trpE mutant vaccine | VO_0002802 | VO_0002806 | merged to Keep ID
Bordetella bronchiseptica bscN and cyaA double mutant vaccine | VO_0002803 | VO_0002804 | merged to Keep ID
B. abortus and B. melitensis mutants with unmarked deletion of asp24, virB2, or manBA | VO_0002810 | VO_0002814\|VO_0002822 | merged to Keep ID
B. melitensis WR201 (16MΔpurEK) | VO_0002820 | VO_0002821 | merged to Keep ID
Edwardsiella tarda aroC/slyA mutant vaccine | VO_0002831 | VO_0002835 | merged to Keep ID
Edwardsiella tarda aroC/esrC mutant vaccine | VO_0002832 | VO_0002834 | merged to Keep ID
Francisella tularensis purMCD mutant vaccine | VO_0002849 | VO_0002851 | merged to Keep ID
Neisseria meningitidis metH/siaD mutant vaccine | VO_0002858 | VO_0002860 | merged to Keep ID
Neisseria meningitidis rfaF/siaD mutant vaccine | VO_0002859 | VO_0002861 | merged to Keep ID
Aro-deleted S. Typhi | VO_0002864 | VO_0002866 | merged to Keep ID
Salmonella Enteritidis guaBA/clpP mutant vaccine | VO_0002871 | VO_0002884\|VO_0002890 | VO_0002890, merged to VO_0002881 based on comment
Salmonella Gallinarum cbiA/cobS mutant vaccine | VO_0002870 | VO_0002875 | merged to Keep ID
Salmonella Typhimurium gyrA/cpxA/rpoB mutant vaccine | VO_0002876 | VO_0002907\|VO_0002891 | merged to Keep ID
Salmonella Gallinarum cpxR/Ion mutant vaccine | VO_0002877 | VO_0002894 | merged to Keep ID
Salmonella Typhimurium cya/crp mutant vaccine | VO_0002878 | VO_0002880 | merged to Keep ID
Salmonella enterica fliC/guaB mutant vaccine | VO_0002881 | VO_0002889 | merged to Keep ID
Salmonella Typhimurium guaBA/clpP mutant vaccine | VO_0002885 | VO_0002873\|VO_0002887 | VO_0002873, merged to VO_0002872 based on comment
Salmonella Typhimurium guaBA/clpP/fliD mutant vaccine | VO_0002882 | VO_0002888\|VO_0002874\|VO_0002886 | VO_0002874, merged to VO_0002872 based on comment, VO:0002886, VO:0002888, merged to VO:0002885 based on comment
Salmonella Typhimurium IppB/msbB mutant vaccine | VO_0002897 | VO_0002899 | merged to Keep ID
Salmonella Typhimurium IppA/IppB/msbB | VO_0002895 | VO_0002898\|VO_0002896 | merged to Keep ID
Salmonella Gallinarum relA/spoT mutant vaccine | VO_0002905 | VO_0002910 | merged to Keep ID
Salmonella Typhimurium asd/rfc mutant vaccine | VO_0002868 | VO_0002906 | merged to Keep ID
Salmonella Typhimurium znuABC mutant vaccine | VO_0002915 | VO_0002917\|VO_0002916 | merged to Keep ID
CVD 1204(pGA1-CS2) | VO_0000733 | VO_0002918 | VO_0002918, merged to VO_0002920 based on comment
SC602 | VO_0000663 | VO_0002926 | VO_0002926, merged to VO_0002920 based on comment
Shigella sonnei virG/senA/senB/msbB2 mutant vaccine | VO_0002927 | VO_0002929\|VO_0002931\|VO_0002933 | VO_0002929, VO_0002931 merged to VO_0002928, VO_0002933 merged to VO_0000678, and relabel the terms
Shigella sonnei virG/senA/senB mutant vaccine | VO_0002928 | VO_0002930\|VO_0002932 | VO_0002932 merged to VO_0000678, VO_0002930 merged to VO_0002928 and relabel the term
Yersinia pestis guaBA mutant vaccine | VO_0002939 | VO_0002940 | merged to Keep ID
Yersinia pestis smpB/ssrA mutant vaccine | VO_0002944 | VO_0002945 | merged to Keep ID
Feline infectiour peritonitis virus 3abc mutant vaccine | VO_0002961 | VO_0002963\|VO_0002962 | merged to Keep ID
Feline infectious peritonitis virus 7ab mutant vaccine | VO_0002964 | VO_0002965 | merged to Keep ID
Herpes simplex virus type 1 DNA vaccine encoding GE | VO_0011423 | VO_0002975 | merged to Keep ID
Pseudorabies virus glycoprotein E/G/UL23 mutant vaccine | VO_0002983 | VO_0002984\|VO_0002988 | merged to Keep ID
Pseudorabies virus gp50/gp63 mutant vaccine | VO_0002986 | VO_0002987 | merged to Keep ID
VEE Virus PE2/E1 mutant vaccine | VO_0002996 | VO_0002997 | merged to Keep ID
WEEV Subunit E2 Protein Vaccine | VO_0011506 | VO_0003001 | VO_0003001 merged to VO_0003002
Western equine encephalomyelitis virus PE2/E2 mutant virus | VO_0003002 | VO_0003004 | VO_0003004 merged to VO_0003003 and relabel the term
P. yoelii p36/p52 mutant vaccine | VO_0003009 | VO_0003010 | merged to Keep ID
Toxoplasma gondii OMPDC/UP mutant vaccine | VO_0003014 | VO_0003015 | merged to Keep ID
0.65 ML Varicella-Zoster Virus Vaccine Live (Oka-Merck) strain 29800 UNT/ML Injection | VO_0003272 | VO_0003280 | merged to Keep ID
WEEV DNA Vaccine encoding 6K-E1 Protein | VO_0011505 | VO_0002999 | VO_0002999 deprecated, label and definition do not match.

**Comment by zhengj2007** [comment]
All issues resolved
