### ISSUE TITLE
VAC: GLA-Alum

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#650]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=83

Chemical Nature:
• Synthetic derivative of natural compound
• Combination adjuvant
• Mineral salt

Mechanism of Action: Innate Immune Activation
Immune profile induced: Th1-biased

Route of immunization: SQ, IM
Point of Contact: Valerie Soza, Access to Advanced Health Institute (AAHI)

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=37454145
https://www.ncbi.nlm.nih.gov/pubmed/?term=24556505
https://www.ncbi.nlm.nih.gov/pubmed/?term=28828575
https://www.ncbi.nlm.nih.gov/pubmed/?term=30013570
https://www.ncbi.nlm.nih.gov/pubmed/?term=24211167
https://www.ncbi.nlm.nih.gov/pubmed/?term=23933525
https://www.ncbi.nlm.nih.gov/pubmed/?term=34597297
https://www.ncbi.nlm.nih.gov/pubmed/?term=36996185
https://www.ncbi.nlm.nih.gov/pubmed/?term=28464026

Ongoing clinical trials:
https://clinicaltrials.gov/ct2/show/NCT03910972
https://clinicaltrials.gov/ct2/show/NCT02126462
https://clinicaltrials.gov/ct2/show/NCT02839161
https://clinicaltrials.gov/ct2/show/NCT03110757
https://clinicaltrials.gov/ct2/show/NCT02337855
https://clinicaltrials.gov/ct2/show/NCT01717950
https://clinicaltrials.gov/ct2/show/NCT02476773
https://clinicaltrials.gov/ct2/show/NCT01261130
https://clinicaltrials.gov/ct2/show/NCT01385189
https://clinicaltrials.gov/ct2/show/NCT03172975

**Comment by zhengj2007** [comment]
Hi @nkosar, I am working on the term you submitted. Could you please add the definition? Thanks!

**Comment by nkosar** [comment]
@zhengj2007 hi, just making sure you want the definition for only vaccine adjuvant #654 and not all of the ones you are currently reviewing submitted by me.

**Comment by nkosar** [comment]
@zhengj2007 also is the definition that you are looking for the chemical nature of the adjuvants or something else?

**Comment by zhengj2007** [comment]
@nkosar The definition I mean is the detailed description of the vaccine adjuvant including its chemical nature, mechanism of Action, etc. that you have provided. 

Here is one example, [CAF09b vaccine adjuvant](http://purl.obolibrary.org/obo/VO_0005473): CAF09b is a liposome-based vaccine adjuvant that is based on cationic surfactant dimethyl-dioctadecyl ammonium (DDA) combined with C-type lectin agonist monomycoloyl glycerol (MMG) and TLR3 agonist poly I:C. CAF09b is able to induce CD8+ T-cell response.

**Comment by nkosar** [comment]
@zhengj2007  Ok got it, a good definition for this adjuvant is "combination adjuvant of a synthetic TLR agonist and aluminum salt" since it is TH-1-inducer.

**Comment by zhengj2007** [comment]
Thanks @nkosar

**Comment by zhengj2007** [comment]
Added in VO, with ID: VO_0006099
