### ISSUE TITLE
VAC: SLA-Alum

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#651]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=82

Chemical Nature:
• Synthetic derivative of natural compound
• Combination adjuvant
• Mineral salt

Mechanism of Action: Innate Immune Activation
Immune profile induced: Th1-biased

Route of immunization: IM
Point of Contact: Valerie Soza, Access to Advanced Health Institute (AAHI)

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=26901122
https://www.ncbi.nlm.nih.gov/pubmed/?term=32983577

Ongoing clinical trials:
none

**Comment by zhengj2007** [comment]
Hi @nkosar, I am working on the term you submitted. Could you please add the definition? Thanks!

**Comment by nkosar** [comment]
@zhengj2007 definition "combination adjuvant of a synthetic TLR4 agonist and aluminum salt"

**Comment by zhengj2007** [comment]
Added in VO, with ID: VO_0006100

**Comment by nkosar** [comment]
@zhengj2007 Hi, this might be a problem on my end but when I try accessing the VO ID it tells me that the term was not found. Let me know if this is a general issue or if only on my end. [https://ontobee.org/ontology/VO?iri=http://purl.obolibrary.org/obo/VO_0006100](url)

**Comment by zhengj2007** [comment]
@nkosar The term is added. However, you cannot find it on the website until we make the VO release and load it into the ontobee. I will contact @yongqunh for the following steps.

**Comment by zhengj2007** [comment]
@nkosar Could you please try the link: http://purl.obolibrary.org/obo/VO_0006100

**Comment by nkosar** [comment]
@zhengj2007 this link worked, thanks!
