### ISSUE TITLE
VAC: Stable Emulsion (SE)

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#652]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=84

Chemical Nature: Emulsion
Mechanism of Action: n/a
Immune profile induced: Mixed Th1/Th2

Route of immunization: IM, SQ
Point of Contact: Valerie Soza, Access to Advanced Health Institute (AAHI)

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=19679214
https://www.ncbi.nlm.nih.gov/pubmed/?term=22896687
https://www.ncbi.nlm.nih.gov/pubmed/?term=28429728
https://www.ncbi.nlm.nih.gov/pubmed/?term=37495191
https://www.ncbi.nlm.nih.gov/pubmed/?term=36256646
https://www.ncbi.nlm.nih.gov/pubmed/?term=28089141

Ongoing clinical trials:
https://clinicaltrials.gov/ct2/show/NCT03330899
https://clinicaltrials.gov/ct2/show/NCT01612000
https://clinicaltrials.gov/ct2/show/NCT02464163
https://clinicaltrials.gov/ct2/show/NCT02464163

**Comment by zhengj2007** [comment]
Hi @nkosar, I am working on the term you submitted. Could you please add the definition? Thanks!

**Comment by nkosar** [comment]
@zhengj2007 definition for this adjuvant "squalene-based oil-in-water emulsion"

**Comment by zhengj2007** [comment]
Added in VO, with ID: VO_0006101
