### ISSUE TITLE
VAC: Precision Vaccines Program (PVP)-057

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#676]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=86

Chemical Nature: Small molecule
Mechanism of Action: Activation of innate immunity
Immune profile induced: Mixed Th1/Th2

Route of immunization: IM, ID
Point of Contact: Ofer Levy, Precision Vaccines Program at Boston Children's Hospital

Pubmed References:
none

Ongoing clinical trials:
none

**Comment by zhengj2007** [comment]
Assigne ID: VO_0006105

Add definition: A vaccine adjuvant which is a small molecule adjuvant that is able to induce a mixed Th1/Th2 response and active innate immunity.

**Comment by zhengj2007** [comment]
@nkosar I would appreciate it very much if you can provide the definition when submit a NTR in the future. Thanks!

**Comment by zhengj2007** [comment]
[precision vaccines program-057 vaccine adjuvant](http://purl.obolibrary.org/obo/VO_0006105)
