### ISSUE TITLE
Add a new vaccine type 'whole cell cancer vaccine'

### ISSUE THREAD

**Issue by yongqunh** [vaccineontology/VO#683]
We (Hayleigh Kahn and Oliver He) would like to propose a new vaccine type term to VO:

term label:
 'whole cell cancer vaccine'

Proposed Definition:
 'whole cell cancer vaccine' is a cancer vaccine that uses whole cells to deliver cancer antigen(s). 

Ref: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3356993/

Note that the whole cell can be tumor cells. In this case, it's a "whole tumor cell cancer vaccine' which can be a subclass of the above term. Ref: https://www.nature.com/articles/s41416-023-02327-6 . There can be other types of whole cell cancer vacccines.

**Comment by zhengj2007** [comment]
whole cell cancer vaccine VO_0007658
whole tumor cell cancer vaccine VO_0007659
