### ISSUE TITLE
VAC: Cowpea mosaic virus

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#684]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=93

Chemical Nature: Nucleoprotein complex
Mechanism of Action: recognized by PRRs 
Immune profile induced: Th1-biased
Definition: particulate antigen delivery system

Route of immunization: Intratumoral, intraperitoneally , IV
Point of Contact: Nicole Steinmetz, University of California, San Diego

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=26689376
https://www.ncbi.nlm.nih.gov/pubmed/?term=37844250

Ongoing clinical trials:
none

**Comment by zhengj2007** [comment]
Cowpea mosaic virus
[NCBITaxon_12264](http://purl.obolibrary.org/obo/NCBITaxon_12264)

**Comment by zhengj2007** [comment]
Considering Cowpea mosaic virus vaccine adjuvant is not exactly same as NCBITaxon_12264 'Cowpea mosaic virus', added 'Cowpea mosaic virus vaccine adjuvant' in VO with ID: VO:0006107.

**Comment by zhengj2007** [comment]
@nkosar I added the [Cowpea mosaic virus vaccine adjuvant](http://purl.obolibrary.org/obo/VO_0006107) in VO. Could you please replace [NCBITaxon_12264](http://purl.obolibrary.org/obo/NCBITaxon_12264) with [VO_0006107](http://purl.obolibrary.org/obo/VO_0006107)? Thanks!

**Comment by nkosar** [comment]
@zhengj2007 Okay I updated it, thank you!
