### ISSUE TITLE
VAC: ACM-CpG

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#690]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=92

Chemical Nature:  Nucleic acid, Emulsion
Mechanism of Action: Innate Immune Activation, preferential uptake by APCs
Immune profile induced: Th1-biased
Definition: TLR-agonist for target; nucleic acid-based adjuvant for chemical nature

Route of immunization: SQ, IN, IM
Point of Contact: Madhavan Nallani, ACM Biolabs

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=34618423
https://www.ncbi.nlm.nih.gov/pubmed/?term=36223228

Ongoing clinical trials:
https://clinicaltrials.gov/ct2/show/NCT05385991

**Comment by nkosar** [comment]
More description for composition: this is both, a nucleic acid adjuvant AND an emulsion (DNA in an emulsion).

**Comment by zhengj2007** [comment]
Assigned ID: VO_0006106
