### ISSUE TITLE
VAC: Nexavant

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#694]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=94 
 
Chemical Nature: dsRNA
Mechanism of Action: TLR3 agonist 
Immune profile induced: Mixed Th1/Th2
Definition: 
- category: nucleic-acid based adjuvant (TLR-agonist)
- synthetic derivative of natural compound

Route of immunization: IM
Point of Contact: Seungbin Cha, NA Vaccine Institute

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=36761735
https://www.ncbi.nlm.nih.gov/pubmed/?term=38136298

Ongoing clinical trials:
none

**Comment by zhengj2007** [comment]
Added 'nexavant vaccine adjuvant' with ID: VO:0006108

**Comment by zhengj2007** [comment]
@nkosar The term is available on the ontobee: [nexavant vaccine adjuvant](http://purl.obolibrary.org/obo/VO_0006108).
