### ISSUE TITLE
New IR Terms

### ISSUE THREAD

**Issue by Huffmaar** [vaccineontology/VO#7]
Please add the following new terms to expand characterization of immune response.
1. Add as subclass vaccine-induced T-helper 1 type immune response (VO_0000100)
  vaccine specific interferon-γ immune response 
  vaccine specific interleukin-2 immune response
  vaccine specific immunoglobin G2a immune response
  vaccine specific TNF-α immune response
vaccine-induced T-helper 2 type immune response (VO_0000101)
 vaccine specific interleukin-4 response
 vaccine specific interleukin-10 response
 vaccine specific immunoglobin G1 response

**Comment by Huffmaar** [comment]
IG2a, IG1 response should be included as antibody responses on further discussion.

**Comment by yongqunh** [comment]
IgG2a is indeed an indicator of Th1 response, and IgG1 is an indicator of Th2 response. 
Reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC101669/

**Comment by yongqunh** [comment]
vaccine specific TNF-α immune response --> may not be classified as Th1 response.

**Comment by yongqunh** [comment]
Terms added:
vaccine specific Th1 immune response indicated by IgG2a  production - VO_0004919
vaccine specific IL-2 immune response - VO_0004916
vaccine specific interferon-γ immune response - VO_0004915
vaccine specific Th2 immune response indicated by IgG1  production - VO_0004920
vaccine specific interleukin-10 response - VO_0004918
vaccine specific interleukin-4 response - VO_0004917
