### ISSUE TITLE
duplicated labels

### ISSUE THREAD

**Issue by zhengj2007** [vaccineontology/VO#737]
Duplicate_Con_1 | D_Label1 | Duplicate_Con_2 | D_Label2
-- | -- | -- | --
obo.VO_0015315 | hepatitis a vaccine  inactivated  strain hm175 injectable suspension | obo.VO_0019505 | hepatitis a vaccine  inactivated  strain hm175 injectable suspension
obo.VO_0020275 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution | obo.VO_0020469 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution
obo.VO_0020276 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe | obo.VO_0020472 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe
obo.VO_0007572 | ad5-ycd/muttksr39rep-hil12 vaccine | obo.VO_0007196 | ad5-ycd/muttksr39rep-hil12 vaccine
obo.VO_0020470 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe [typhim vi] | obo.VO_0020277 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe [typhim vi]
obo.VO_0020472 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe | obo.VO_0020276 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe
obo.VO_0020409 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] | obo.VO_0020410 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi]
obo.VO_0003234 | 0.5 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection | obo.VO_0019179 | 0.5 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection
obo.VO_0019529 | hepatitis b surface antigen vaccine 0.04 mg/ml | obo.VO_0003230 | hepatitis b surface antigen vaccine 0.04 mg/ml
obo.VO_0019362 | 1 ml hepatitis a vaccine  inactivated  strain hm175 1440 unt/ml prefilled syringe | obo.VO_0015196 | 1 ml hepatitis a vaccine  inactivated  strain hm175 1440 unt/ml prefilled syringe
obo.VO_0007535 | fowlpox virus vaccine | obo.VO_0001463 | fowlpox virus vaccine
obo.VO_0020444 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 | obo.VO_0020445 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1
obo.VO_0020410 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] | obo.VO_0020409 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi]
obo.VO_0020445 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 | obo.VO_0020444 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1
obo.VO_0019351 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe | obo.VO_0020475 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe
obo.VO_0020433 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by sanofi | obo.VO_0020432 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by sanofi
obo.VO_0004216 | bacillus anthracis strain v770-np1-r antigens 0.1 mg/ml [biothrax] | obo.VO_0019407 | bacillus anthracis strain v770-np1-r antigens 0.1 mg/ml [biothrax]
obo.VO_0004213 | bacillus anthracis strain v770-np1-r antigens 0.1 mg/ml | obo.VO_0019406 | bacillus anthracis strain v770-np1-r antigens 0.1 mg/ml
obo.VO_0003964 | vibrio cholerae cvd 103-hgr strain live antigen 12000000 unt/ml [vaxchora] | obo.VO_0020290 | vibrio cholerae cvd 103-hgr strain live antigen 12000000 unt/ml [vaxchora]
obo.VO_0003956 | vibrio cholerae cvd 103-hgr strain live antigen 12000000 unt/ml | obo.VO_0020289 | vibrio cholerae cvd 103-hgr strain live antigen 12000000 unt/ml
obo.VO_0010127 | historical diphtheria and tetanus toxoids and acellular pertussis  poliovirus  haemophilus b conjugate and hepatitis b  recombinant  vaccine. | obo.VO_0010162 | historical diphtheria and tetanus toxoids and acellular pertussis  poliovirus  haemophilus b conjugate and hepatitis b  recombinant  vaccine.
obo.VO_0020465 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by waymade | obo.VO_0020466 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by waymade
obo.VO_0020463 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by sanofi | obo.VO_0020464 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by sanofi
obo.VO_0020434 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by waymade | obo.VO_0020435 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by waymade
obo.VO_0020421 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 | obo.VO_0020420 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1
obo.VO_0010162 | historical diphtheria and tetanus toxoids and acellular pertussis  poliovirus  haemophilus b conjugate and hepatitis b  recombinant  vaccine. | obo.VO_0010127 | historical diphtheria and tetanus toxoids and acellular pertussis  poliovirus  haemophilus b conjugate and hepatitis b  recombinant  vaccine.
obo.VO_0020462 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by waymade | obo.VO_0020461 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by waymade
obo.VO_0020422 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 | obo.VO_0020423 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10
obo.VO_0020277 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe [typhim vi] | obo.VO_0020470 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe [typhim vi]
obo.VO_0019175 | 0.5 ml hepatitis a vaccine  inactivated  strain hm175 1440 unt/ml prefilled syringe | obo.VO_0015110 | 0.5 ml hepatitis a vaccine  inactivated  strain hm175 1440 unt/ml prefilled syringe
obo.VO_0020466 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by waymade | obo.VO_0020465 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by waymade
obo.VO_0001463 | fowlpox virus vaccine | obo.VO_0007535 | fowlpox virus vaccine
obo.VO_0020460 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by sanofi | obo.VO_0020459 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by sanofi
obo.VO_0019505 | hepatitis a vaccine  inactivated  strain hm175 injectable suspension | obo.VO_0015315 | hepatitis a vaccine  inactivated  strain hm175 injectable suspension
obo.VO_0003228 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection [recombivax] | obo.VO_0019370 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection [recombivax]
obo.VO_0003233 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection | obo.VO_0019369 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection
obo.VO_0020475 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe | obo.VO_0019351 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe
obo.VO_0019370 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection [recombivax] | obo.VO_0003228 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection [recombivax]
obo.VO_0020447 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 | obo.VO_0020446 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10
obo.VO_0020432 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by sanofi | obo.VO_0020433 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by sanofi
obo.VO_0020446 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 | obo.VO_0020447 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10
obo.VO_0020423 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 | obo.VO_0020422 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10
obo.VO_0019406 | bacillus anthracis strain v770-np1-r antigens 0.1 mg/ml | obo.VO_0004213 | bacillus anthracis strain v770-np1-r antigens 0.1 mg/ml
obo.VO_0020464 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by sanofi | obo.VO_0020463 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by sanofi
obo.VO_0020420 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 | obo.VO_0020421 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1
obo.VO_0020459 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by sanofi | obo.VO_0020460 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by sanofi
obo.VO_0019369 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection | obo.VO_0003233 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection
obo.VO_0020461 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by waymade | obo.VO_0020462 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by waymade
obo.VO_0020435 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by waymade | obo.VO_0020434 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by waymade
obo.VO_0003230 | hepatitis b surface antigen vaccine 0.04 mg/ml | obo.VO_0019529 | hepatitis b surface antigen vaccine 0.04 mg/ml

**Comment by zhengj2007** [comment]
fowlpox virus vaccine see #736

**Comment by zhengj2007** [comment]
http://purl.obolibrary.org/obo/VO_0007572
add associated issue tracker: https://github.com/vaccineontology/VO/issues/89
and update term annotations based on information in tracker 89.

deprecated term: http://purl.obolibrary.org/obo/VO_0007196

**Comment by xingxianli** [comment]
[duplicated_label.xlsx](https://github.com/user-attachments/files/17581837/duplicated_label.xlsx)

**Comment by xingxianli** [comment]
Add proposed changes in the tracker (added one more column in original table)
[duplicated_label.xlsx](https://github.com/user-attachments/files/17581858/duplicated_label.xlsx)

**Comment by xingxianli** [comment]
Duplicate_Con_1 | D_Label1 | Duplicate_Con_2 | D_Label2 | proposed change
-- | -- | -- | -- | --
VO:0015315 | hepatitis a vaccine  inactivated  strain hm175 injectable suspension | VO:0019505 | hepatitis a vaccine  inactivated  strain hm175 injectable suspension | delete  VO:0019505, merge the information of  VO:0019505  to VO:0015315
VO:0020275 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution | VO:0020469 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution | delete VO:0020275, merge the information of  VO:0020469 to VO:0020275
VO:0020276 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe | VO:0020472 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe | delete VO:0020276, merge annotation
VO:0007572 | ad5-ycd/muttksr39rep-hil12 vaccine | VO:0007196 | ad5-ycd/muttksr39rep-hil12 vaccine | VO:0007196  should be Monoclonal Antibody A1G4 Anti-Idiotype Vaccine, definition of  VO:0007196 and Gene name: IL12B\|Gene name: IL12A of VO:0007196 should be VO:0007572
VO:0020470 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe [typhim vi] | VO:0020277 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe [typhim vi] | merge the VO:0020277 to VO:0020470
VO:0020472 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe | VO:0020276 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe | merge the  VO:0020276 to VO:0020472
VO:0020409 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] | VO:0020410 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0003234 | 0.5 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection | VO:0019179 | 0.5 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection | just delete the VO:0003234
VO:0019529 | hepatitis b surface antigen vaccine 0.04 mg/ml | VO:0003230 | hepatitis b surface antigen vaccine 0.04 mg/ml | delete VO:0019529, move the annotation and subclasses
VO:0019362 | 1 ml hepatitis a vaccine  inactivated  strain hm175 1440 unt/ml prefilled syringe | VO:0015196 | 1 ml hepatitis a vaccine  inactivated  strain hm175 1440 unt/ml prefilled syringe | delete  VO:0015196 , move subclasses
VO:0007535 | fowlpox virus vaccine | VO:0001463 | fowlpox virus vaccine | https://github.com/vaccineontology/VO/issues/736
VO:0020444 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 | VO:0020445 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0019351 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe | VO:0020475 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml prefilled syringe | delete  VO:0020475, move subclass
VO:0020433 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by sanofi | VO:0020432 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by sanofi | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0004216 | bacillus anthracis strain v770-np1-r antigens 0.1 mg/ml [biothrax] | VO:0019407 | bacillus anthracis strain v770-np1-r antigens 0.1 mg/ml [biothrax] | obselete the old one VO:0004216
VO:0004213 | bacillus anthracis strain v770-np1-r antigens 0.1 mg/ml | VO:0019406 | bacillus anthracis strain v770-np1-r antigens 0.1 mg/ml | obselete the old one VO:0004213, move the subclass
VO:0003964 | vibrio cholerae cvd 103-hgr strain live antigen 12000000 unt/ml [vaxchora] | VO:0020290 | vibrio cholerae cvd 103-hgr strain live antigen 12000000 unt/ml [vaxchora] | obselete the old one VO:0003964
VO:0003956 | vibrio cholerae cvd 103-hgr strain live antigen 12000000 unt/ml | VO:0020289 | vibrio cholerae cvd 103-hgr strain live antigen 12000000 unt/ml | obselete the old one VO:0003956
VO:0010127 | historical diphtheria and tetanus toxoids and acellular pertussis  poliovirus  haemophilus b conjugate and hepatitis b  recombinant  vaccine. | VO:0010162 | historical diphtheria and tetanus toxoids and acellular pertussis  poliovirus  haemophilus b conjugate and hepatitis b  recombinant  vaccine. | obselete the old one VO:0010127
VO:0020465 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by waymade | VO:0020466 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by waymade | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0020463 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by sanofi | VO:0020464 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 by sanofi | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0020434 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by waymade | VO:0020435 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] by waymade | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0020421 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 | VO:0020420 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0020462 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by waymade | VO:0020461 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by waymade | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0020422 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 | VO:0020423 | typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0019175 | 0.5 ml hepatitis a vaccine  inactivated  strain hm175 1440 unt/ml prefilled syringe | VO:0015110 | 0.5 ml hepatitis a vaccine  inactivated  strain hm175 1440 unt/ml prefilled syringe | delete  VO:0015110, merge subclasses
VO:0019370 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection [recombivax] | VO:0003228 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection [recombivax] | obselete old one  VO:0003228
VO:0020446 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 | VO:0020447 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 10 | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0020459 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by sanofi | VO:0020460 | 0.5 ml typhoid vi polysaccharide vaccine  s typhi ty2 strain 0.05 mg/ml injectable solution [typhim vi] box of 1 by sanofi | identical term in OMOP, delete the red one(no subclass of that),merge the ID
VO:0019369 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection | VO:0003233 | 1 ml hepatitis b surface antigen vaccine 0.04 mg/ml injection | delete  VO:0003233 , move subclasses
