### ISSUE TITLE
VAC: IL-12-MOP (CTX-1796)

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#740]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=100

Chemical Nature: nucleic acid
Mechanism of Action: Cytokine Receptor
Immune profile induced: Th1-biased

Route of immunization: IM
Point of Contact: Romain Micol, Combined Therapeutics

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=39047117

Ongoing clinical trials:
none

**Comment by zhengj2007** [comment]
Added with label: IL-12-MOP (CTX-1796) vaccine adjuvant and ID: VO_0005509.
