### ISSUE TITLE
VAC: EVAX-B

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#759]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=101

Chemical Nature: Emulsion
Mechanism of Action: Botryococcene oil-in-water emulsion
Immune profile induced: Mixed Th1/Th2

Route of immunization: SQ
Point of Contact: Chase Kempinski , EVAX Inc.

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=33051497

Ongoing clinical trials:
none

**Comment by zhengj2007** [comment]
Added and assigned ID: VO_0005510
Will be available on the ontobee site in 1-2 weeks.

**Comment by zhengj2007** [comment]
@nkosar Term is available on http://purl.obolibrary.org/obo/VO_0005510
