### ISSUE TITLE
VAC: ME-F-1051 (VesiVax®)

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#784]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=104

Chemical Nature: VesiVax® liposome
Mechanism of Action: none
Immune profile induced: none

Route of immunization: SQ prime and IN boost, SQ, Combination sub-cheek, IN and ID, IN prime and sub-cheek boosts
Point of Contact: Gary Fujii, Molecular Express

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=16713037
https://www.ncbi.nlm.nih.gov/pubmed/?term=17981684
https://www.ncbi.nlm.nih.gov/pubmed/?term=19835825
https://www.ncbi.nlm.nih.gov/pubmed/?term=21545821
https://www.ncbi.nlm.nih.gov/pubmed/?term=23313243
https://www.ncbi.nlm.nih.gov/pubmed/?term=26312747
https://www.ncbi.nlm.nih.gov/pubmed/?term=27997339
https://www.ncbi.nlm.nih.gov/pubmed/?term=28922045
https://www.ncbi.nlm.nih.gov/pubmed/?term=29420901
https://www.ncbi.nlm.nih.gov/pubmed/?term=3568049

Ongoing clinical trials:
none

**Comment by zhengj2007** [comment]
Added in VO and assigned ID: VO_0005512
