### ISSUE TITLE
VAC: CpG 1018

### ISSUE THREAD

**Issue by nkosar** [vaccineontology/VO#787]
Request to add a new vaccine adjuvant as seen in VAC:
https://vac.niaid.nih.gov/view?id=105

Chemical Nature: Nucleic acid
Mechanism of Action: CpG 1018 is a short class B CpG-containing sequence with phosphorothioate-linked nucleotides
Immune profile induced: Th1-biased

Route of immunization: IN, IM
Point of Contact: Ben Wizel, Dynavax 

Pubmed References:
https://www.ncbi.nlm.nih.gov/pubmed/?term=24464743 
https://www.ncbi.nlm.nih.gov/pubmed/?term=33649322
https://www.ncbi.nlm.nih.gov/pubmed/?term=33873199
https://www.ncbi.nlm.nih.gov/pubmed/?term=33888840
https://www.ncbi.nlm.nih.gov/pubmed/?term=38570604
https://www.ncbi.nlm.nih.gov/pubmed/?term=35927132
https://www.ncbi.nlm.nih.gov/pubmed/?term=35869085
https://www.ncbi.nlm.nih.gov/pubmed/?term=37703367
https://www.ncbi.nlm.nih.gov/pubmed/?term=39231203

Ongoing clinical trials:
https://clinicaltrials.gov/ct2/show/ACTRN12624000064505
https://clinicaltrials.gov/ct2/show/NCT06334393
https://clinicaltrials.gov/ct2/show/NCT04177355
https://clinicaltrials.gov/ct2/show/NCT04672395
https://clinicaltrials.gov/ct2/show/NCT05188677
https://clinicaltrials.gov/ct2/show/NCT05011526
https://clinicaltrials.gov/ct2/show/NCT05364242
https://clinicaltrials.gov/ct2/show/NCT04956224
https://clinicaltrials.gov/ct2/show/NCT0486456
https://clinicaltrials.gov/ct2/show/ACTRN12620001177943
https://clinicaltrials.gov/ct2/show/NCT00251394
https://clinicaltrials.gov/ct2/show/NCT01282762
https://clinicaltrials.gov/ct2/show/NCT00346086
https://clinicaltrials.gov/ct2/show/NCT06569823
https://clinicaltrials.gov/ct2/show/NCT05245838
https://clinicaltrials.gov/ct2/show/NCT05506969

**Comment by zhengj2007** [comment]
Added in VO and assigned ID: VO_0005514

**Comment by zhengj2007** [comment]
@nkosar Hi Nilufer, We are preparing a VO paper and going to submit to scientific data (Due July 22nd). Since you contributed to VO development (vaccine adjuvants), we'd like to include you as the co-author of the paper? If you agree, could you please provide your email address, affiliation (we prefer to use the one where you requested the VAC terms0, and ORCID? When I have your  email address, I will share the draft paper with you. Thanks!
Jie
