### ISSUE TITLE
12 Melanoma Peptide Vaccine

### ISSUE THREAD

**Issue by ISeleznev822** [vaccineontology/VO#80]
Vaccine name: 12 Melanoma Peptide Vaccine
Cancer type: n/a
Vaccine type: other
Host: Human
Description: n/a
Immunization Route: n/a
PubMed: n/a
Gene/protein: n/a
VIOLIN link: http://www.violinet.org/canvaxkb/vaccine_detail.php?c_vaccine_id=5418&keywords=

**Comment by zhengj2007** [comment]
Cannot find corresponding VIOLIN record.
It should be 12MP Vaccine, see https://github.com/vaccineontology/VO/issues/81.

Merged VO_0007188 to VO_0007189 12MP Vaccine and deprecated VO_0007188.
